// Generated by Haxe 4.3.7
#include <hxcpp.h>

#ifndef INCLUDED_Std
#include <Std.h>
#endif
#ifndef INCLUDED_haxe_Log
#include <haxe/Log.h>
#endif
#ifndef INCLUDED_lime_system_BackendThread
#include <lime/system/BackendThread.h>
#endif
#ifndef INCLUDED_lime_system_CFFI
#include <lime/system/CFFI.h>
#endif

HX_LOCAL_STACK_FRAME(_hx_pos_0770abc70ebf45ce_14_start,"lime.system.BackendThread","start",0xbeea358c,"lime.system.BackendThread.start","lime/system/BackendThread.hx",14,0x20804dc6)
HX_LOCAL_STACK_FRAME(_hx_pos_0770abc70ebf45ce_25_stop,"lime.system.BackendThread","stop",0xa06d0218,"lime.system.BackendThread.stop","lime/system/BackendThread.hx",25,0x20804dc6)
HX_LOCAL_STACK_FRAME(_hx_pos_0770abc70ebf45ce_36_run,"lime.system.BackendThread","run",0x346029f5,"lime.system.BackendThread.run","lime/system/BackendThread.hx",36,0x20804dc6)
HX_LOCAL_STACK_FRAME(_hx_pos_0770abc70ebf45ce_45_boot,"lime.system.BackendThread","boot",0x952c9648,"lime.system.BackendThread.boot","lime/system/BackendThread.hx",45,0x20804dc6)
HX_LOCAL_STACK_FRAME(_hx_pos_0770abc70ebf45ce_46_boot,"lime.system.BackendThread","boot",0x952c9648,"lime.system.BackendThread.boot","lime/system/BackendThread.hx",46,0x20804dc6)
HX_LOCAL_STACK_FRAME(_hx_pos_0770abc70ebf45ce_47_boot,"lime.system.BackendThread","boot",0x952c9648,"lime.system.BackendThread.boot","lime/system/BackendThread.hx",47,0x20804dc6)
namespace lime{
namespace _hx_system{

void BackendThread_obj::__construct() { }

Dynamic BackendThread_obj::__CreateEmpty() { return new BackendThread_obj; }

void *BackendThread_obj::_hx_vtable = 0;

Dynamic BackendThread_obj::__Create(::hx::DynamicArray inArgs)
{
	::hx::ObjectPtr< BackendThread_obj > _hx_result = new BackendThread_obj();
	_hx_result->__construct();
	return _hx_result;
}

bool BackendThread_obj::_hx_isInstanceOf(int inClassId) {
	return inClassId==(int)0x00000001 || inClassId==(int)0x09322b1a;
}

void BackendThread_obj::start(){
            	HX_STACKFRAME(&_hx_pos_0770abc70ebf45ce_14_start)
HXDLIN(  14)		try {
            			HX_STACK_CATCHABLE( ::Dynamic, 0);
HXLINE(  15)			::lime::_hx_system::BackendThread_obj::lime_backend_thread_start();
            		} catch( ::Dynamic _hx_e) {
            			if (_hx_e.IsClass<  ::Dynamic >() ){
            				HX_STACK_BEGIN_CATCH
            				 ::Dynamic _g = _hx_e;
HXLINE(  16)				{
HXLINE(  16)					null();
            				}
HXDLIN(  16)				 ::Dynamic e = _g;
HXLINE(  17)				{
HXLINE(  17)					 ::Dynamic _hx_tmp = ::haxe::Log_obj::trace;
HXDLIN(  17)					::String _hx_tmp1 = (HX_("[BackendThread] Error: Native bindings missing. Please run 'lime rebuild windows'. Details: ",45,07,a9,e7) + ::Std_obj::string(e));
HXDLIN(  17)					_hx_tmp(_hx_tmp1,::hx::SourceInfo(HX_("lime/system/BackendThread.hx",c6,4d,80,20),17,HX_("lime.system.BackendThread",18,86,48,ce),HX_("start",62,74,0b,84)));
            				}
            			}
            			else {
            				HX_STACK_DO_THROW(_hx_e);
            			}
            		}
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC0(BackendThread_obj,start,(void))

void BackendThread_obj::stop(){
            	HX_STACKFRAME(&_hx_pos_0770abc70ebf45ce_25_stop)
HXDLIN(  25)		try {
            			HX_STACK_CATCHABLE( ::Dynamic, 0);
HXLINE(  26)			::lime::_hx_system::BackendThread_obj::lime_backend_thread_stop();
            		} catch( ::Dynamic _hx_e) {
            			if (_hx_e.IsClass<  ::Dynamic >() ){
            				HX_STACK_BEGIN_CATCH
            				 ::Dynamic _g = _hx_e;
HXLINE(  27)				{
HXLINE(  27)					null();
            				}
            			}
            			else {
            				HX_STACK_DO_THROW(_hx_e);
            			}
            		}
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC0(BackendThread_obj,stop,(void))

void BackendThread_obj::run( ::Dynamic callback){
            	HX_STACKFRAME(&_hx_pos_0770abc70ebf45ce_36_run)
HXDLIN(  36)		try {
            			HX_STACK_CATCHABLE( ::Dynamic, 0);
HXLINE(  37)			::lime::_hx_system::BackendThread_obj::lime_backend_thread_run(callback);
            		} catch( ::Dynamic _hx_e) {
            			if (_hx_e.IsClass<  ::Dynamic >() ){
            				HX_STACK_BEGIN_CATCH
            				 ::Dynamic _g = _hx_e;
HXLINE(  38)				{
HXLINE(  38)					null();
            				}
HXLINE(  39)				::haxe::Log_obj::trace(HX_("[BackendThread] Error: Cannot run task. Native library may be outdated.",f1,f1,bf,39),::hx::SourceInfo(HX_("lime/system/BackendThread.hx",c6,4d,80,20),39,HX_("lime.system.BackendThread",18,86,48,ce),HX_("run",4b,e7,56,00)));
            			}
            			else {
            				HX_STACK_DO_THROW(_hx_e);
            			}
            		}
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC1(BackendThread_obj,run,(void))

 ::Dynamic BackendThread_obj::lime_backend_thread_start;

 ::Dynamic BackendThread_obj::lime_backend_thread_stop;

 ::Dynamic BackendThread_obj::lime_backend_thread_run;


BackendThread_obj::BackendThread_obj()
{
}

bool BackendThread_obj::__GetStatic(const ::String &inName, Dynamic &outValue, ::hx::PropertyAccess inCallProp)
{
	switch(inName.length) {
	case 3:
		if (HX_FIELD_EQ(inName,"run") ) { outValue = run_dyn(); return true; }
		break;
	case 4:
		if (HX_FIELD_EQ(inName,"stop") ) { outValue = stop_dyn(); return true; }
		break;
	case 5:
		if (HX_FIELD_EQ(inName,"start") ) { outValue = start_dyn(); return true; }
		break;
	case 23:
		if (HX_FIELD_EQ(inName,"lime_backend_thread_run") ) { outValue = ( lime_backend_thread_run ); return true; }
		break;
	case 24:
		if (HX_FIELD_EQ(inName,"lime_backend_thread_stop") ) { outValue = ( lime_backend_thread_stop ); return true; }
		break;
	case 25:
		if (HX_FIELD_EQ(inName,"lime_backend_thread_start") ) { outValue = ( lime_backend_thread_start ); return true; }
	}
	return false;
}

bool BackendThread_obj::__SetStatic(const ::String &inName,Dynamic &ioValue,::hx::PropertyAccess inCallProp)
{
	switch(inName.length) {
	case 23:
		if (HX_FIELD_EQ(inName,"lime_backend_thread_run") ) { lime_backend_thread_run=ioValue.Cast<  ::Dynamic >(); return true; }
		break;
	case 24:
		if (HX_FIELD_EQ(inName,"lime_backend_thread_stop") ) { lime_backend_thread_stop=ioValue.Cast<  ::Dynamic >(); return true; }
		break;
	case 25:
		if (HX_FIELD_EQ(inName,"lime_backend_thread_start") ) { lime_backend_thread_start=ioValue.Cast<  ::Dynamic >(); return true; }
	}
	return false;
}

#ifdef HXCPP_SCRIPTABLE
static ::hx::StorageInfo *BackendThread_obj_sMemberStorageInfo = 0;
static ::hx::StaticInfo BackendThread_obj_sStaticStorageInfo[] = {
	{::hx::fsObject /*  ::Dynamic */ ,(void *) &BackendThread_obj::lime_backend_thread_start,HX_("lime_backend_thread_start",e2,f0,61,52)},
	{::hx::fsObject /*  ::Dynamic */ ,(void *) &BackendThread_obj::lime_backend_thread_stop,HX_("lime_backend_thread_stop",82,83,46,8b)},
	{::hx::fsObject /*  ::Dynamic */ ,(void *) &BackendThread_obj::lime_backend_thread_run,HX_("lime_backend_thread_run",cb,43,fd,12)},
	{ ::hx::fsUnknown, 0, null()}
};
#endif

static void BackendThread_obj_sMarkStatics(HX_MARK_PARAMS) {
	HX_MARK_MEMBER_NAME(BackendThread_obj::lime_backend_thread_start,"lime_backend_thread_start");
	HX_MARK_MEMBER_NAME(BackendThread_obj::lime_backend_thread_stop,"lime_backend_thread_stop");
	HX_MARK_MEMBER_NAME(BackendThread_obj::lime_backend_thread_run,"lime_backend_thread_run");
};

#ifdef HXCPP_VISIT_ALLOCS
static void BackendThread_obj_sVisitStatics(HX_VISIT_PARAMS) {
	HX_VISIT_MEMBER_NAME(BackendThread_obj::lime_backend_thread_start,"lime_backend_thread_start");
	HX_VISIT_MEMBER_NAME(BackendThread_obj::lime_backend_thread_stop,"lime_backend_thread_stop");
	HX_VISIT_MEMBER_NAME(BackendThread_obj::lime_backend_thread_run,"lime_backend_thread_run");
};

#endif

::hx::Class BackendThread_obj::__mClass;

static ::String BackendThread_obj_sStaticFields[] = {
	HX_("start",62,74,0b,84),
	HX_("stop",02,f0,5b,4c),
	HX_("run",4b,e7,56,00),
	HX_("lime_backend_thread_start",e2,f0,61,52),
	HX_("lime_backend_thread_stop",82,83,46,8b),
	HX_("lime_backend_thread_run",cb,43,fd,12),
	::String(null())
};

void BackendThread_obj::__register()
{
	BackendThread_obj _hx_dummy;
	BackendThread_obj::_hx_vtable = *(void **)&_hx_dummy;
	::hx::Static(__mClass) = new ::hx::Class_obj();
	__mClass->mName = HX_("lime.system.BackendThread",18,86,48,ce);
	__mClass->mSuper = &super::__SGetClass();
	__mClass->mConstructEmpty = &__CreateEmpty;
	__mClass->mConstructArgs = &__Create;
	__mClass->mGetStaticField = &BackendThread_obj::__GetStatic;
	__mClass->mSetStaticField = &BackendThread_obj::__SetStatic;
	__mClass->mMarkFunc = BackendThread_obj_sMarkStatics;
	__mClass->mStatics = ::hx::Class_obj::dupFunctions(BackendThread_obj_sStaticFields);
	__mClass->mMembers = ::hx::Class_obj::dupFunctions(0 /* sMemberFields */);
	__mClass->mCanCast = ::hx::TCanCast< BackendThread_obj >;
#ifdef HXCPP_VISIT_ALLOCS
	__mClass->mVisitFunc = BackendThread_obj_sVisitStatics;
#endif
#ifdef HXCPP_SCRIPTABLE
	__mClass->mMemberStorageInfo = BackendThread_obj_sMemberStorageInfo;
#endif
#ifdef HXCPP_SCRIPTABLE
	__mClass->mStaticStorageInfo = BackendThread_obj_sStaticStorageInfo;
#endif
	::hx::_hx_RegisterClass(__mClass->mName, __mClass);
}

void BackendThread_obj::__boot()
{
{
            	HX_STACKFRAME(&_hx_pos_0770abc70ebf45ce_45_boot)
HXDLIN(  45)		lime_backend_thread_start = ::lime::_hx_system::CFFI_obj::load(HX_("lime",15,17,b3,47),HX_("lime_backend_thread_start",e2,f0,61,52),0,true);
            	}
{
            	HX_STACKFRAME(&_hx_pos_0770abc70ebf45ce_46_boot)
HXDLIN(  46)		lime_backend_thread_stop = ::lime::_hx_system::CFFI_obj::load(HX_("lime",15,17,b3,47),HX_("lime_backend_thread_stop",82,83,46,8b),0,true);
            	}
{
            	HX_STACKFRAME(&_hx_pos_0770abc70ebf45ce_47_boot)
HXDLIN(  47)		lime_backend_thread_run = ::lime::_hx_system::CFFI_obj::load(HX_("lime",15,17,b3,47),HX_("lime_backend_thread_run",cb,43,fd,12),1,true);
            	}
}

} // end namespace lime
} // end namespace system
