// Generated by Haxe 4.3.7
#include <hxcpp.h>

#ifndef INCLUDED_openfl_events_Event
#include <openfl/events/Event.h>
#endif
#ifndef INCLUDED_openfl_events_TextEditEvent
#include <openfl/events/TextEditEvent.h>
#endif

HX_DEFINE_STACK_FRAME(_hx_pos_43aabe54a487eb88_17_new,"openfl.events.TextEditEvent","new",0x2fde379e,"openfl.events.TextEditEvent.new","openfl/events/TextEditEvent.hx",17,0x1997d7b2)
HX_LOCAL_STACK_FRAME(_hx_pos_43aabe54a487eb88_25_clone,"openfl.events.TextEditEvent","clone",0x3cc4461b,"openfl.events.TextEditEvent.clone","openfl/events/TextEditEvent.hx",25,0x1997d7b2)
HX_LOCAL_STACK_FRAME(_hx_pos_43aabe54a487eb88_35_toString,"openfl.events.TextEditEvent","toString",0x00ef68ae,"openfl.events.TextEditEvent.toString","openfl/events/TextEditEvent.hx",35,0x1997d7b2)
static const ::String _hx_array_data_508ed0ac_3[] = {
	HX_("type",ba,f2,08,4d),HX_("bubbles",67,bb,56,61),HX_("cancelable",14,a0,79,c4),HX_("text",ad,cc,f9,4c),HX_("start",62,74,0b,84),HX_("length",e6,94,07,9f),
};
HX_LOCAL_STACK_FRAME(_hx_pos_43aabe54a487eb88_39___init,"openfl.events.TextEditEvent","__init",0xd55ed1b2,"openfl.events.TextEditEvent.__init","openfl/events/TextEditEvent.hx",39,0x1997d7b2)
HX_LOCAL_STACK_FRAME(_hx_pos_43aabe54a487eb88_10_boot,"openfl.events.TextEditEvent","boot",0xaaab7334,"openfl.events.TextEditEvent.boot","openfl/events/TextEditEvent.hx",10,0x1997d7b2)
namespace openfl{
namespace events{

void TextEditEvent_obj::__construct(::String type,::hx::Null< bool >  __o_bubbles,::hx::Null< bool >  __o_cancelable,::String __o_text,::hx::Null< int >  __o_start,::hx::Null< int >  __o_length){
            		bool bubbles = __o_bubbles.Default(false);
            		bool cancelable = __o_cancelable.Default(false);
            		::String text = __o_text;
            		if (::hx::IsNull(__o_text)) text = HX_("",00,00,00,00);
            		int start = __o_start.Default(0);
            		int length = __o_length.Default(0);
            	HX_STACKFRAME(&_hx_pos_43aabe54a487eb88_17_new)
HXLINE(  18)		super::__construct(type,bubbles,cancelable);
HXLINE(  19)		this->text = text;
HXLINE(  20)		this->start = start;
HXLINE(  21)		this->length = length;
            	}

Dynamic TextEditEvent_obj::__CreateEmpty() { return new TextEditEvent_obj; }

void *TextEditEvent_obj::_hx_vtable = 0;

Dynamic TextEditEvent_obj::__Create(::hx::DynamicArray inArgs)
{
	::hx::ObjectPtr< TextEditEvent_obj > _hx_result = new TextEditEvent_obj();
	_hx_result->__construct(inArgs[0],inArgs[1],inArgs[2],inArgs[3],inArgs[4],inArgs[5]);
	return _hx_result;
}

bool TextEditEvent_obj::_hx_isInstanceOf(int inClassId) {
	if (inClassId<=(int)0x08ec4c31) {
		return inClassId==(int)0x00000001 || inClassId==(int)0x08ec4c31;
	} else {
		return inClassId==(int)0x7f9dcf7e;
	}
}

 ::openfl::events::Event TextEditEvent_obj::clone(){
            	HX_GC_STACKFRAME(&_hx_pos_43aabe54a487eb88_25_clone)
HXLINE(  26)		 ::openfl::events::TextEditEvent event =  ::openfl::events::TextEditEvent_obj::__alloc( HX_CTX ,this->type,this->bubbles,this->cancelable,this->text,this->start,this->length);
HXLINE(  27)		event->target = this->target;
HXLINE(  28)		event->currentTarget = this->currentTarget;
HXLINE(  29)		event->eventPhase = this->eventPhase;
HXLINE(  30)		return event;
            	}


::String TextEditEvent_obj::toString(){
            	HX_STACKFRAME(&_hx_pos_43aabe54a487eb88_35_toString)
HXDLIN(  35)		return this->_hx___formatToString(HX_("TextEditEvent",23,af,1b,09),::Array_obj< ::String >::fromData( _hx_array_data_508ed0ac_3,6));
            	}


void TextEditEvent_obj::_hx___init(){
            	HX_STACKFRAME(&_hx_pos_43aabe54a487eb88_39___init)
HXLINE(  40)		this->super::_hx___init();
HXLINE(  41)		this->text = HX_("",00,00,00,00);
HXLINE(  42)		this->start = 0;
HXLINE(  43)		this->length = 0;
            	}


::String TextEditEvent_obj::TEXT_EDIT;


::hx::ObjectPtr< TextEditEvent_obj > TextEditEvent_obj::__new(::String type,::hx::Null< bool >  __o_bubbles,::hx::Null< bool >  __o_cancelable,::String __o_text,::hx::Null< int >  __o_start,::hx::Null< int >  __o_length) {
	::hx::ObjectPtr< TextEditEvent_obj > __this = new TextEditEvent_obj();
	__this->__construct(type,__o_bubbles,__o_cancelable,__o_text,__o_start,__o_length);
	return __this;
}

::hx::ObjectPtr< TextEditEvent_obj > TextEditEvent_obj::__alloc(::hx::Ctx *_hx_ctx,::String type,::hx::Null< bool >  __o_bubbles,::hx::Null< bool >  __o_cancelable,::String __o_text,::hx::Null< int >  __o_start,::hx::Null< int >  __o_length) {
	TextEditEvent_obj *__this = (TextEditEvent_obj*)(::hx::Ctx::alloc(_hx_ctx, sizeof(TextEditEvent_obj), true, "openfl.events.TextEditEvent"));
	*(void **)__this = TextEditEvent_obj::_hx_vtable;
	__this->__construct(type,__o_bubbles,__o_cancelable,__o_text,__o_start,__o_length);
	return __this;
}

TextEditEvent_obj::TextEditEvent_obj()
{
}

void TextEditEvent_obj::__Mark(HX_MARK_PARAMS)
{
	HX_MARK_BEGIN_CLASS(TextEditEvent);
	HX_MARK_MEMBER_NAME(text,"text");
	HX_MARK_MEMBER_NAME(start,"start");
	HX_MARK_MEMBER_NAME(length,"length");
	 ::openfl::events::Event_obj::__Mark(HX_MARK_ARG);
	HX_MARK_END_CLASS();
}

void TextEditEvent_obj::__Visit(HX_VISIT_PARAMS)
{
	HX_VISIT_MEMBER_NAME(text,"text");
	HX_VISIT_MEMBER_NAME(start,"start");
	HX_VISIT_MEMBER_NAME(length,"length");
	 ::openfl::events::Event_obj::__Visit(HX_VISIT_ARG);
}

::hx::Val TextEditEvent_obj::__Field(const ::String &inName,::hx::PropertyAccess inCallProp)
{
	switch(inName.length) {
	case 4:
		if (HX_FIELD_EQ(inName,"text") ) { return ::hx::Val( text ); }
		break;
	case 5:
		if (HX_FIELD_EQ(inName,"start") ) { return ::hx::Val( start ); }
		if (HX_FIELD_EQ(inName,"clone") ) { return ::hx::Val( clone_dyn() ); }
		break;
	case 6:
		if (HX_FIELD_EQ(inName,"length") ) { return ::hx::Val( length ); }
		if (HX_FIELD_EQ(inName,"__init") ) { return ::hx::Val( _hx___init_dyn() ); }
		break;
	case 8:
		if (HX_FIELD_EQ(inName,"toString") ) { return ::hx::Val( toString_dyn() ); }
	}
	return super::__Field(inName,inCallProp);
}

::hx::Val TextEditEvent_obj::__SetField(const ::String &inName,const ::hx::Val &inValue,::hx::PropertyAccess inCallProp)
{
	switch(inName.length) {
	case 4:
		if (HX_FIELD_EQ(inName,"text") ) { text=inValue.Cast< ::String >(); return inValue; }
		break;
	case 5:
		if (HX_FIELD_EQ(inName,"start") ) { start=inValue.Cast< int >(); return inValue; }
		break;
	case 6:
		if (HX_FIELD_EQ(inName,"length") ) { length=inValue.Cast< int >(); return inValue; }
	}
	return super::__SetField(inName,inValue,inCallProp);
}

void TextEditEvent_obj::__GetFields(Array< ::String> &outFields)
{
	outFields->push(HX_("text",ad,cc,f9,4c));
	outFields->push(HX_("start",62,74,0b,84));
	outFields->push(HX_("length",e6,94,07,9f));
	super::__GetFields(outFields);
};

#ifdef HXCPP_SCRIPTABLE
static ::hx::StorageInfo TextEditEvent_obj_sMemberStorageInfo[] = {
	{::hx::fsString,(int)offsetof(TextEditEvent_obj,text),HX_("text",ad,cc,f9,4c)},
	{::hx::fsInt,(int)offsetof(TextEditEvent_obj,start),HX_("start",62,74,0b,84)},
	{::hx::fsInt,(int)offsetof(TextEditEvent_obj,length),HX_("length",e6,94,07,9f)},
	{ ::hx::fsUnknown, 0, null()}
};
static ::hx::StaticInfo TextEditEvent_obj_sStaticStorageInfo[] = {
	{::hx::fsString,(void *) &TextEditEvent_obj::TEXT_EDIT,HX_("TEXT_EDIT",1c,06,0b,64)},
	{ ::hx::fsUnknown, 0, null()}
};
#endif

static ::String TextEditEvent_obj_sMemberFields[] = {
	HX_("text",ad,cc,f9,4c),
	HX_("start",62,74,0b,84),
	HX_("length",e6,94,07,9f),
	HX_("clone",5d,13,63,48),
	HX_("toString",ac,d0,6e,38),
	HX_("__init",30,9e,b3,f4),
	::String(null()) };

static void TextEditEvent_obj_sMarkStatics(HX_MARK_PARAMS) {
	HX_MARK_MEMBER_NAME(TextEditEvent_obj::TEXT_EDIT,"TEXT_EDIT");
};

#ifdef HXCPP_VISIT_ALLOCS
static void TextEditEvent_obj_sVisitStatics(HX_VISIT_PARAMS) {
	HX_VISIT_MEMBER_NAME(TextEditEvent_obj::TEXT_EDIT,"TEXT_EDIT");
};

#endif

::hx::Class TextEditEvent_obj::__mClass;

static ::String TextEditEvent_obj_sStaticFields[] = {
	HX_("TEXT_EDIT",1c,06,0b,64),
	::String(null())
};

void TextEditEvent_obj::__register()
{
	TextEditEvent_obj _hx_dummy;
	TextEditEvent_obj::_hx_vtable = *(void **)&_hx_dummy;
	::hx::Static(__mClass) = new ::hx::Class_obj();
	__mClass->mName = HX_("openfl.events.TextEditEvent",ac,d0,8e,50);
	__mClass->mSuper = &super::__SGetClass();
	__mClass->mConstructEmpty = &__CreateEmpty;
	__mClass->mConstructArgs = &__Create;
	__mClass->mGetStaticField = &::hx::Class_obj::GetNoStaticField;
	__mClass->mSetStaticField = &::hx::Class_obj::SetNoStaticField;
	__mClass->mMarkFunc = TextEditEvent_obj_sMarkStatics;
	__mClass->mStatics = ::hx::Class_obj::dupFunctions(TextEditEvent_obj_sStaticFields);
	__mClass->mMembers = ::hx::Class_obj::dupFunctions(TextEditEvent_obj_sMemberFields);
	__mClass->mCanCast = ::hx::TCanCast< TextEditEvent_obj >;
#ifdef HXCPP_VISIT_ALLOCS
	__mClass->mVisitFunc = TextEditEvent_obj_sVisitStatics;
#endif
#ifdef HXCPP_SCRIPTABLE
	__mClass->mMemberStorageInfo = TextEditEvent_obj_sMemberStorageInfo;
#endif
#ifdef HXCPP_SCRIPTABLE
	__mClass->mStaticStorageInfo = TextEditEvent_obj_sStaticStorageInfo;
#endif
	::hx::_hx_RegisterClass(__mClass->mName, __mClass);
}

void TextEditEvent_obj::__boot()
{
{
            	HX_STACKFRAME(&_hx_pos_43aabe54a487eb88_10_boot)
HXDLIN(  10)		TEXT_EDIT = HX_("textEdit",57,1d,0a,46);
            	}
}

} // end namespace openfl
} // end namespace events
