// Generated by Haxe 4.3.7
#ifndef INCLUDED_hxvlc_openfl_AudioGroup
#define INCLUDED_hxvlc_openfl_AudioGroup

#ifndef HXCPP_H
#include <hxcpp.h>
#endif

HX_DECLARE_CLASS2(hxvlc,openfl,Audio)
HX_DECLARE_CLASS2(hxvlc,openfl,AudioGroup)
HX_DECLARE_CLASS2(lime,app,_Event_Single_Void)
HX_DECLARE_CLASS2(lime,app,_Event_String_Void)
HX_DECLARE_CLASS2(lime,app,_Event_Void_Void)
HX_DECLARE_CLASS2(lime,app,_Event_haxe_Int64_Void)
HX_DECLARE_CLASS2(openfl,events,EventDispatcher)
HX_DECLARE_CLASS2(openfl,events,IEventDispatcher)

namespace hxvlc{
namespace openfl{


class HXCPP_CLASS_ATTRIBUTES AudioGroup_obj : public ::hx::Object
{
	public:
		typedef ::hx::Object super;
		typedef AudioGroup_obj OBJ_;
		AudioGroup_obj();

	public:
		enum { _hx_ClassId = 0x5602baf2 };

		void __construct();
		inline void *operator new(size_t inSize, bool inContainer=true,const char *inName="hxvlc.openfl.AudioGroup")
			{ return ::hx::Object::operator new(inSize,inContainer,inName); }
		inline void *operator new(size_t inSize, int extra)
			{ return ::hx::Object::operator new(inSize+extra,true,"hxvlc.openfl.AudioGroup"); }
		static ::hx::ObjectPtr< AudioGroup_obj > __new();
		static ::hx::ObjectPtr< AudioGroup_obj > __alloc(::hx::Ctx *_hx_ctx);
		static void * _hx_vtable;
		static Dynamic __CreateEmpty();
		static Dynamic __Create(::hx::DynamicArray inArgs);
		//~AudioGroup_obj();

		HX_DO_RTTI_ALL;
		::hx::Val __Field(const ::String &inString, ::hx::PropertyAccess inCallProp);
		::hx::Val __SetField(const ::String &inString,const ::hx::Val &inValue, ::hx::PropertyAccess inCallProp);
		void __GetFields(Array< ::String> &outFields);
		static void __register();
		void __Mark(HX_MARK_PARAMS);
		void __Visit(HX_VISIT_PARAMS);
		bool _hx_isInstanceOf(int inClassId);
		::String __ToString() const { return HX_("AudioGroup",a9,e6,fe,2f); }

		::Array< ::Dynamic> members;
		 ::lime::app::_Event_Void_Void onOpening;
		 ::lime::app::_Event_Void_Void onPlaying;
		 ::lime::app::_Event_Void_Void onStopped;
		 ::lime::app::_Event_Void_Void onPaused;
		 ::lime::app::_Event_Void_Void onEndReached;
		 ::lime::app::_Event_String_Void onEncounteredError;
		 ::lime::app::_Event_haxe_Int64_Void onTimeChanged;
		 ::lime::app::_Event_Single_Void onPositionChanged;
		 ::lime::app::_Event_haxe_Int64_Void onLengthChanged;
		bool autoDestroy;
		 ::hxvlc::openfl::Audio _firstMember;
		float _volume;
		 ::Dynamic _dispatchOpening;
		Dynamic _dispatchOpening_dyn() { return _dispatchOpening;}
		 ::Dynamic _dispatchPlaying;
		Dynamic _dispatchPlaying_dyn() { return _dispatchPlaying;}
		 ::Dynamic _dispatchStopped;
		Dynamic _dispatchStopped_dyn() { return _dispatchStopped;}
		 ::Dynamic _dispatchPaused;
		Dynamic _dispatchPaused_dyn() { return _dispatchPaused;}
		 ::Dynamic _dispatchEndReached;
		Dynamic _dispatchEndReached_dyn() { return _dispatchEndReached;}
		 ::Dynamic _dispatchEncounteredError;
		Dynamic _dispatchEncounteredError_dyn() { return _dispatchEncounteredError;}
		 ::Dynamic _dispatchTimeChanged;
		Dynamic _dispatchTimeChanged_dyn() { return _dispatchTimeChanged;}
		 ::Dynamic _dispatchPositionChanged;
		Dynamic _dispatchPositionChanged_dyn() { return _dispatchPositionChanged;}
		 ::Dynamic _dispatchLengthChanged;
		Dynamic _dispatchLengthChanged_dyn() { return _dispatchLengthChanged;}
		void add( ::hxvlc::openfl::Audio audio);
		::Dynamic add_dyn();

		void remove( ::hxvlc::openfl::Audio audio);
		::Dynamic remove_dyn();

		bool addTrack(::String location,::Array< ::String > options,::hx::Null< int >  id);
		::Dynamic addTrack_dyn();

		void addTrackAsync(::String location,::Array< ::String > options,::hx::Null< int >  id, ::Dynamic onComplete);
		::Dynamic addTrackAsync_dyn();

		void releaseMedia(int id);
		::Dynamic releaseMedia_dyn();

		void play(::hx::Null< int >  delay);
		::Dynamic play_dyn();

		void pause();
		::Dynamic pause_dyn();

		void resume();
		::Dynamic resume_dyn();

		void stop();
		::Dynamic stop_dyn();

		void setTime(::cpp::Int64 time);
		::Dynamic setTime_dyn();

		void dispose();
		::Dynamic dispose_dyn();

		::cpp::Int64 get_length();
		::Dynamic get_length_dyn();

		::cpp::Int64 get_duration();
		::Dynamic get_duration_dyn();

		::cpp::Int64 get_time();
		::Dynamic get_time_dyn();

		::cpp::Int64 set_time(::cpp::Int64 value);
		::Dynamic set_time_dyn();

		float get_position();
		::Dynamic get_position_dyn();

		float set_position(float value);
		::Dynamic set_position_dyn();

		float get_volume();
		::Dynamic get_volume_dyn();

		float set_volume(float value);
		::Dynamic set_volume_dyn();

		float get_rate();
		::Dynamic get_rate_dyn();

		float set_rate(float value);
		::Dynamic set_rate_dyn();

		bool get_isPlaying();
		::Dynamic get_isPlaying_dyn();

		void updateFirstMemberListeners();
		::Dynamic updateFirstMemberListeners_dyn();

		void detachFirstMemberListeners();
		::Dynamic detachFirstMemberListeners_dyn();

		void attachFirstMemberListeners();
		::Dynamic attachFirstMemberListeners_dyn();

};

} // end namespace hxvlc
} // end namespace openfl

#endif /* INCLUDED_hxvlc_openfl_AudioGroup */ 
