// Generated by Haxe 4.3.7
#ifndef INCLUDED_hxvlc_openfl_Audio
#define INCLUDED_hxvlc_openfl_Audio

#ifndef HXCPP_H
#include <hxcpp.h>
#endif

#ifndef INCLUDED_openfl_events_EventDispatcher
#include <openfl/events/EventDispatcher.h>
#endif
#ifndef INCLUDED_f6e4a6bd16e728f7
#define INCLUDED_f6e4a6bd16e728f7
#include "vlc/vlc.h"
#endif
HX_DECLARE_CLASS0(EReg)
HX_DECLARE_CLASS2(haxe,io,BytesInput)
HX_DECLARE_CLASS2(haxe,io,Input)
HX_DECLARE_CLASS2(hxvlc,openfl,Audio)
HX_DECLARE_CLASS2(hxvlc,util,Stats)
HX_DECLARE_CLASS2(hxvlc,util,TrackDescription)
HX_DECLARE_CLASS2(lime,app,_Event_Int_Int_Void)
HX_DECLARE_CLASS2(lime,app,_Event_Int_Void)
HX_DECLARE_CLASS2(lime,app,_Event_Single_Void)
HX_DECLARE_CLASS2(lime,app,_Event_String_Void)
HX_DECLARE_CLASS2(lime,app,_Event_Void_Void)
HX_DECLARE_CLASS2(lime,app,_Event_haxe_Int64_Void)
HX_DECLARE_CLASS2(openfl,events,EventDispatcher)
HX_DECLARE_CLASS2(openfl,events,IEventDispatcher)
HX_DECLARE_CLASS2(sys,thread,Mutex)

namespace hxvlc{
namespace openfl{


class HXCPP_CLASS_ATTRIBUTES Audio_obj : public  ::openfl::events::EventDispatcher_obj
{
	public:
		typedef  ::openfl::events::EventDispatcher_obj super;
		typedef Audio_obj OBJ_;
		Audio_obj();

	public:
		enum { _hx_ClassId = 0x4d160da9 };

		void __construct();
		inline void *operator new(size_t inSize, bool inContainer=true,const char *inName="hxvlc.openfl.Audio")
			{ return ::hx::Object::operator new(inSize,inContainer,inName); }
		inline void *operator new(size_t inSize, int extra)
			{ return ::hx::Object::operator new(inSize+extra,true,"hxvlc.openfl.Audio"); }
		static ::hx::ObjectPtr< Audio_obj > __new();
		static ::hx::ObjectPtr< Audio_obj > __alloc(::hx::Ctx *_hx_ctx);
		static void * _hx_vtable;
		static Dynamic __CreateEmpty();
		static Dynamic __Create(::hx::DynamicArray inArgs);
		//~Audio_obj();

		HX_DO_RTTI_ALL;
		::hx::Val __Field(const ::String &inString, ::hx::PropertyAccess inCallProp);
		static bool __GetStatic(const ::String &inString, Dynamic &outValue, ::hx::PropertyAccess inCallProp);
		::hx::Val __SetField(const ::String &inString,const ::hx::Val &inValue, ::hx::PropertyAccess inCallProp);
		static bool __SetStatic(const ::String &inString, Dynamic &ioValue, ::hx::PropertyAccess inCallProp);
		void __GetFields(Array< ::String> &outFields);
		static void __register();
		void __Mark(HX_MARK_PARAMS);
		void __Visit(HX_VISIT_PARAMS);
		bool _hx_isInstanceOf(int inClassId);
		::String __ToString() const { return HX_("Audio",b6,e8,ad,ba); }

		static void __boot();
		static int MAX_AUDIO_BUFFER_COUNT;
		static  ::EReg URL_VERIFICATION_REGEX;
		Float syncStartTime;
		::cpp::Int64 _syncStartPts;
		float groupVolume;
		 ::lime::app::_Event_Void_Void onOpening;
		 ::lime::app::_Event_Void_Void onPlaying;
		 ::lime::app::_Event_Void_Void onStopped;
		 ::lime::app::_Event_Void_Void onPaused;
		 ::lime::app::_Event_Void_Void onEndReached;
		 ::lime::app::_Event_String_Void onEncounteredError;
		 ::lime::app::_Event_Void_Void onMediaChanged;
		 ::lime::app::_Event_Int_Int_Void onESAdded;
		 ::lime::app::_Event_Int_Int_Void onESDeleted;
		 ::lime::app::_Event_Int_Int_Void onESSelected;
		 ::lime::app::_Event_Void_Void onCorked;
		 ::lime::app::_Event_Void_Void onUncorked;
		 ::lime::app::_Event_haxe_Int64_Void onTimeChanged;
		 ::lime::app::_Event_Single_Void onPositionChanged;
		 ::lime::app::_Event_haxe_Int64_Void onLengthChanged;
		 ::lime::app::_Event_Int_Void onChapterChanged;
		 ::lime::app::_Event_Void_Void onMediaMetaChanged;
		 ::lime::app::_Event_Int_Void onMediaParsedChanged;
		 ::sys::thread::Mutex mediaMutex;
		 ::sys::thread::Mutex alMutex;
		 ::haxe::io::BytesInput mediaInput;
		::cpp::Pointer<  libvlc_media_player_t > mediaPlayer;
		::Array< int > _attachedEventTypes;
		bool _closing;
		bool _disposed;
		::cpp::Int64 _cachedTime;
		Float _cachedTimestamp;
		 ::Dynamic alUseEXTFLOAT32;
		 ::Dynamic alUseEXTMCFORMATS;
		 ::Dynamic alSource;
		::cpp::VirtualArray alBufferPool;
		::Array< unsigned char > alSamples;
		unsigned int alSampleRate;
		int alFormat;
		unsigned int alFrameSize;
		bool load( ::Dynamic location,::Array< ::String > options);
		::Dynamic load_dyn();

		void loadAsync( ::Dynamic location,::Array< ::String > options, ::Dynamic onComplete, ::Dynamic onError);
		::Dynamic loadAsync_dyn();

		void releaseMedia();
		::Dynamic releaseMedia_dyn();

		bool loadFromSubItem(int index,::Array< ::String > options);
		::Dynamic loadFromSubItem_dyn();

		bool parseWithOptions(int parse_flag,int timeout);
		::Dynamic parseWithOptions_dyn();

		void parseStop();
		::Dynamic parseStop_dyn();

		bool addSlave(int type,::String url,bool select);
		::Dynamic addSlave_dyn();

		::Array< ::Dynamic> getAudioDescription();
		::Dynamic getAudioDescription_dyn();

		bool play();
		::Dynamic play_dyn();

		void stop();
		::Dynamic stop_dyn();

		void pause();
		::Dynamic pause_dyn();

		void resume();
		::Dynamic resume_dyn();

		void togglePaused();
		::Dynamic togglePaused_dyn();

		void previousChapter();
		::Dynamic previousChapter_dyn();

		void nextChapter();
		::Dynamic nextChapter_dyn();

		::String getMeta(int e_meta);
		::Dynamic getMeta_dyn();

		void setMeta(int e_meta,::String value);
		::Dynamic setMeta_dyn();

		bool saveMeta();
		::Dynamic saveMeta_dyn();

		void dispose();
		::Dynamic dispose_dyn();

		void onExit(int code);
		::Dynamic onExit_dyn();

		::String get_mrl();
		::Dynamic get_mrl_dyn();

		 ::hxvlc::util::Stats get_stats();
		::Dynamic get_stats_dyn();

		::cpp::Int64 get_duration();
		::Dynamic get_duration_dyn();

		bool get_isPlaying();
		::Dynamic get_isPlaying_dyn();

		::cpp::Int64 get_length();
		::Dynamic get_length_dyn();

		::cpp::Int64 get_time();
		::Dynamic get_time_dyn();

		::cpp::Int64 set_time(::cpp::Int64 value);
		::Dynamic set_time_dyn();

		float get_position();
		::Dynamic get_position_dyn();

		float set_position(float value);
		::Dynamic set_position_dyn();

		int get_chapter();
		::Dynamic get_chapter_dyn();

		int set_chapter(int value);
		::Dynamic set_chapter_dyn();

		int get_chapterCount();
		::Dynamic get_chapterCount_dyn();

		float get_rate();
		::Dynamic get_rate_dyn();

		float set_rate(float value);
		::Dynamic set_rate_dyn();

		bool get_isSeekable();
		::Dynamic get_isSeekable_dyn();

		bool get_canPause();
		::Dynamic get_canPause_dyn();

		float get_volume();
		::Dynamic get_volume_dyn();

		float set_volume(float value);
		::Dynamic set_volume_dyn();

		int get_role();
		::Dynamic get_role_dyn();

		int set_role(int value);
		::Dynamic set_role_dyn();

		int get_audioTrackCount();
		::Dynamic get_audioTrackCount_dyn();

		int get_audioTrack();
		::Dynamic get_audioTrack_dyn();

		int set_audioTrack(int value);
		::Dynamic set_audioTrack_dyn();

		::cpp::Int64 get_audioDelay();
		::Dynamic get_audioDelay_dyn();

		::cpp::Int64 set_audioDelay(::cpp::Int64 value);
		::Dynamic set_audioDelay_dyn();

		int mediaOpen(::cpp::UInt64* sizep);

		ssize_t mediaRead(unsigned char* buf,size_t len);

		int mediaSeek(::cpp::UInt64 offset);

		void audioPlay(unsigned char* samples,unsigned int count,::cpp::Int64 pts);

		void audioResume(::cpp::Int64 pts);

		void audioPause(::cpp::Int64 pts);

		void audioFlush(::cpp::Int64 pts);

		int audioSetup(char* format,unsigned int* rate,unsigned int* channels);

		void audioSetVolume(float volume,bool mute);

		void eventManagerCallbacks(const  libvlc_event_t* p_event);

		bool isValid();

		void getDescription(::cpp::Pointer<  libvlc_track_description_t > rawDescription,::Array< ::Dynamic> description);

		void setMediaToPlayer(::cpp::Pointer<  libvlc_media_t > mediaItem,::Array< ::String > options);

		void setupAudio();

		void setupEvents();

		void addEvent(::cpp::Pointer<  libvlc_event_manager_t > eventManager,int type);

		void detachEvents();

};

} // end namespace hxvlc
} // end namespace openfl

#endif /* INCLUDED_hxvlc_openfl_Audio */ 
