// Generated by Haxe 4.3.7
#ifndef INCLUDED_lime_system_BackendThread
#define INCLUDED_lime_system_BackendThread

#ifndef HXCPP_H
#include <hxcpp.h>
#endif

HX_DECLARE_CLASS2(lime,_hx_system,BackendThread)

namespace lime{
namespace _hx_system{


class HXCPP_CLASS_ATTRIBUTES BackendThread_obj : public ::hx::Object
{
	public:
		typedef ::hx::Object super;
		typedef BackendThread_obj OBJ_;
		BackendThread_obj();

	public:
		enum { _hx_ClassId = 0x09322b1a };

		void __construct();
		inline void *operator new(size_t inSize, bool inContainer=false,const char *inName="lime.system.BackendThread")
			{ return ::hx::Object::operator new(inSize,inContainer,inName); }
		inline void *operator new(size_t inSize, int extra)
			{ return ::hx::Object::operator new(inSize+extra,false,"lime.system.BackendThread"); }

		inline static ::hx::ObjectPtr< BackendThread_obj > __new() {
			::hx::ObjectPtr< BackendThread_obj > __this = new BackendThread_obj();
			__this->__construct();
			return __this;
		}

		inline static ::hx::ObjectPtr< BackendThread_obj > __alloc(::hx::Ctx *_hx_ctx) {
			BackendThread_obj *__this = (BackendThread_obj*)(::hx::Ctx::alloc(_hx_ctx, sizeof(BackendThread_obj), false, "lime.system.BackendThread"));
			*(void **)__this = BackendThread_obj::_hx_vtable;
			return __this;
		}

		static void * _hx_vtable;
		static Dynamic __CreateEmpty();
		static Dynamic __Create(::hx::DynamicArray inArgs);
		//~BackendThread_obj();

		HX_DO_RTTI_ALL;
		static bool __GetStatic(const ::String &inString, Dynamic &outValue, ::hx::PropertyAccess inCallProp);
		static bool __SetStatic(const ::String &inString, Dynamic &ioValue, ::hx::PropertyAccess inCallProp);
		static void __register();
		bool _hx_isInstanceOf(int inClassId);
		::String __ToString() const { return HX_("BackendThread",de,41,e8,e8); }

		static void __boot();
		static void start();
		static ::Dynamic start_dyn();

		static void stop();
		static ::Dynamic stop_dyn();

		static void run( ::Dynamic callback);
		static ::Dynamic run_dyn();

		static  ::Dynamic lime_backend_thread_start;
		static Dynamic lime_backend_thread_start_dyn() { return lime_backend_thread_start;}
		static  ::Dynamic lime_backend_thread_stop;
		static Dynamic lime_backend_thread_stop_dyn() { return lime_backend_thread_stop;}
		static  ::Dynamic lime_backend_thread_run;
		static Dynamic lime_backend_thread_run_dyn() { return lime_backend_thread_run;}
};

} // end namespace lime
} // end namespace system

#endif /* INCLUDED_lime_system_BackendThread */ 
