// Generated by Haxe 4.3.7
#include <hxcpp.h>

#ifndef INCLUDED_hxvlc_openfl_Audio
#include <hxvlc/openfl/Audio.h>
#endif
#ifndef INCLUDED_hxvlc_openfl_AudioGroup
#include <hxvlc/openfl/AudioGroup.h>
#endif
#ifndef INCLUDED_lime_app__Event_Single_Void
#include <lime/app/_Event_Single_Void.h>
#endif
#ifndef INCLUDED_lime_app__Event_String_Void
#include <lime/app/_Event_String_Void.h>
#endif
#ifndef INCLUDED_lime_app__Event_Void_Void
#include <lime/app/_Event_Void_Void.h>
#endif
#ifndef INCLUDED_lime_app__Event_haxe_Int64_Void
#include <lime/app/_Event_haxe_Int64_Void.h>
#endif
#ifndef INCLUDED_lime_system_System
#include <lime/system/System.h>
#endif
#ifndef INCLUDED_openfl_events_EventDispatcher
#include <openfl/events/EventDispatcher.h>
#endif
#ifndef INCLUDED_openfl_events_IEventDispatcher
#include <openfl/events/IEventDispatcher.h>
#endif

HX_DEFINE_STACK_FRAME(_hx_pos_c45750b9e975401e_10_new,"hxvlc.openfl.AudioGroup","new",0x7cb3c568,"hxvlc.openfl.AudioGroup.new","hxvlc/openfl/AudioGroup.hx",10,0x150c98e8)
HX_LOCAL_STACK_FRAME(_hx_pos_c45750b9e975401e_145_add,"hxvlc.openfl.AudioGroup","add",0x7ca9e729,"hxvlc.openfl.AudioGroup.add","hxvlc/openfl/AudioGroup.hx",145,0x150c98e8)
HX_LOCAL_STACK_FRAME(_hx_pos_c45750b9e975401e_163_remove,"hxvlc.openfl.AudioGroup","remove",0x44197c3c,"hxvlc.openfl.AudioGroup.remove","hxvlc/openfl/AudioGroup.hx",163,0x150c98e8)
HX_LOCAL_STACK_FRAME(_hx_pos_c45750b9e975401e_178_addTrack,"hxvlc.openfl.AudioGroup","addTrack",0x7cff82a2,"hxvlc.openfl.AudioGroup.addTrack","hxvlc/openfl/AudioGroup.hx",178,0x150c98e8)
HX_LOCAL_STACK_FRAME(_hx_pos_c45750b9e975401e_218_addTrackAsync,"hxvlc.openfl.AudioGroup","addTrackAsync",0xeac5213a,"hxvlc.openfl.AudioGroup.addTrackAsync","hxvlc/openfl/AudioGroup.hx",218,0x150c98e8)
HX_LOCAL_STACK_FRAME(_hx_pos_c45750b9e975401e_232_addTrackAsync,"hxvlc.openfl.AudioGroup","addTrackAsync",0xeac5213a,"hxvlc.openfl.AudioGroup.addTrackAsync","hxvlc/openfl/AudioGroup.hx",232,0x150c98e8)
HX_LOCAL_STACK_FRAME(_hx_pos_c45750b9e975401e_238_addTrackAsync,"hxvlc.openfl.AudioGroup","addTrackAsync",0xeac5213a,"hxvlc.openfl.AudioGroup.addTrackAsync","hxvlc/openfl/AudioGroup.hx",238,0x150c98e8)
HX_LOCAL_STACK_FRAME(_hx_pos_c45750b9e975401e_254_addTrackAsync,"hxvlc.openfl.AudioGroup","addTrackAsync",0xeac5213a,"hxvlc.openfl.AudioGroup.addTrackAsync","hxvlc/openfl/AudioGroup.hx",254,0x150c98e8)
HX_LOCAL_STACK_FRAME(_hx_pos_c45750b9e975401e_262_addTrackAsync,"hxvlc.openfl.AudioGroup","addTrackAsync",0xeac5213a,"hxvlc.openfl.AudioGroup.addTrackAsync","hxvlc/openfl/AudioGroup.hx",262,0x150c98e8)
HX_LOCAL_STACK_FRAME(_hx_pos_c45750b9e975401e_275_releaseMedia,"hxvlc.openfl.AudioGroup","releaseMedia",0x93abc795,"hxvlc.openfl.AudioGroup.releaseMedia","hxvlc/openfl/AudioGroup.hx",275,0x150c98e8)
HX_LOCAL_STACK_FRAME(_hx_pos_c45750b9e975401e_288_play,"hxvlc.openfl.AudioGroup","play",0xa1f09fec,"hxvlc.openfl.AudioGroup.play","hxvlc/openfl/AudioGroup.hx",288,0x150c98e8)
HX_LOCAL_STACK_FRAME(_hx_pos_c45750b9e975401e_303_pause,"hxvlc.openfl.AudioGroup","pause",0x09651dfe,"hxvlc.openfl.AudioGroup.pause","hxvlc/openfl/AudioGroup.hx",303,0x150c98e8)
HX_LOCAL_STACK_FRAME(_hx_pos_c45750b9e975401e_312_resume,"hxvlc.openfl.AudioGroup","resume",0x481549a5,"hxvlc.openfl.AudioGroup.resume","hxvlc/openfl/AudioGroup.hx",312,0x150c98e8)
HX_LOCAL_STACK_FRAME(_hx_pos_c45750b9e975401e_320_stop,"hxvlc.openfl.AudioGroup","stop",0xa3f261fa,"hxvlc.openfl.AudioGroup.stop","hxvlc/openfl/AudioGroup.hx",320,0x150c98e8)
HX_LOCAL_STACK_FRAME(_hx_pos_c45750b9e975401e_354_setTime,"hxvlc.openfl.AudioGroup","setTime",0x71b425d7,"hxvlc.openfl.AudioGroup.setTime","hxvlc/openfl/AudioGroup.hx",354,0x150c98e8)
HX_LOCAL_STACK_FRAME(_hx_pos_c45750b9e975401e_362_dispose,"hxvlc.openfl.AudioGroup","dispose",0x1a7f99a7,"hxvlc.openfl.AudioGroup.dispose","hxvlc/openfl/AudioGroup.hx",362,0x150c98e8)
HX_LOCAL_STACK_FRAME(_hx_pos_c45750b9e975401e_375_get_length,"hxvlc.openfl.AudioGroup","get_length",0xfddb40a7,"hxvlc.openfl.AudioGroup.get_length","hxvlc/openfl/AudioGroup.hx",375,0x150c98e8)
HX_LOCAL_STACK_FRAME(_hx_pos_c45750b9e975401e_381_get_duration,"hxvlc.openfl.AudioGroup","get_duration",0x9074ed55,"hxvlc.openfl.AudioGroup.get_duration","hxvlc/openfl/AudioGroup.hx",381,0x150c98e8)
HX_LOCAL_STACK_FRAME(_hx_pos_c45750b9e975401e_387_get_time,"hxvlc.openfl.AudioGroup","get_time",0xba3a558e,"hxvlc.openfl.AudioGroup.get_time","hxvlc/openfl/AudioGroup.hx",387,0x150c98e8)
HX_LOCAL_STACK_FRAME(_hx_pos_c45750b9e975401e_392_set_time,"hxvlc.openfl.AudioGroup","set_time",0x6897af02,"hxvlc.openfl.AudioGroup.set_time","hxvlc/openfl/AudioGroup.hx",392,0x150c98e8)
HX_LOCAL_STACK_FRAME(_hx_pos_c45750b9e975401e_402_get_position,"hxvlc.openfl.AudioGroup","get_position",0x46e17eaa,"hxvlc.openfl.AudioGroup.get_position","hxvlc/openfl/AudioGroup.hx",402,0x150c98e8)
HX_LOCAL_STACK_FRAME(_hx_pos_c45750b9e975401e_407_set_position,"hxvlc.openfl.AudioGroup","set_position",0x5bdaa21e,"hxvlc.openfl.AudioGroup.set_position","hxvlc/openfl/AudioGroup.hx",407,0x150c98e8)
HX_LOCAL_STACK_FRAME(_hx_pos_c45750b9e975401e_417_get_volume,"hxvlc.openfl.AudioGroup","get_volume",0xbe26d59b,"hxvlc.openfl.AudioGroup.get_volume","hxvlc/openfl/AudioGroup.hx",417,0x150c98e8)
HX_LOCAL_STACK_FRAME(_hx_pos_c45750b9e975401e_422_set_volume,"hxvlc.openfl.AudioGroup","set_volume",0xc1a4740f,"hxvlc.openfl.AudioGroup.set_volume","hxvlc/openfl/AudioGroup.hx",422,0x150c98e8)
HX_LOCAL_STACK_FRAME(_hx_pos_c45750b9e975401e_434_get_rate,"hxvlc.openfl.AudioGroup","get_rate",0xb8e1dc61,"hxvlc.openfl.AudioGroup.get_rate","hxvlc/openfl/AudioGroup.hx",434,0x150c98e8)
HX_LOCAL_STACK_FRAME(_hx_pos_c45750b9e975401e_439_set_rate,"hxvlc.openfl.AudioGroup","set_rate",0x673f35d5,"hxvlc.openfl.AudioGroup.set_rate","hxvlc/openfl/AudioGroup.hx",439,0x150c98e8)
HX_LOCAL_STACK_FRAME(_hx_pos_c45750b9e975401e_448_get_isPlaying,"hxvlc.openfl.AudioGroup","get_isPlaying",0x7c31ef83,"hxvlc.openfl.AudioGroup.get_isPlaying","hxvlc/openfl/AudioGroup.hx",448,0x150c98e8)
HX_LOCAL_STACK_FRAME(_hx_pos_c45750b9e975401e_460_updateFirstMemberListeners,"hxvlc.openfl.AudioGroup","updateFirstMemberListeners",0x346ec616,"hxvlc.openfl.AudioGroup.updateFirstMemberListeners","hxvlc/openfl/AudioGroup.hx",460,0x150c98e8)
HX_LOCAL_STACK_FRAME(_hx_pos_c45750b9e975401e_470_detachFirstMemberListeners,"hxvlc.openfl.AudioGroup","detachFirstMemberListeners",0xeea9be60,"hxvlc.openfl.AudioGroup.detachFirstMemberListeners","hxvlc/openfl/AudioGroup.hx",470,0x150c98e8)
HX_LOCAL_STACK_FRAME(_hx_pos_c45750b9e975401e_487_attachFirstMemberListeners,"hxvlc.openfl.AudioGroup","attachFirstMemberListeners",0xde3101d2,"hxvlc.openfl.AudioGroup.attachFirstMemberListeners","hxvlc/openfl/AudioGroup.hx",487,0x150c98e8)
namespace hxvlc{
namespace openfl{

void AudioGroup_obj::__construct(){
            	HX_GC_STACKFRAME(&_hx_pos_c45750b9e975401e_10_new)
HXLINE(  93)		this->_volume = ( (float)(((Float)1.0)) );
HXLINE(  90)		this->_firstMember = null();
HXLINE(  87)		this->autoDestroy = false;
HXLINE(  42)		this->onLengthChanged =  ::lime::app::_Event_haxe_Int64_Void_obj::__alloc( HX_CTX );
HXLINE(  39)		this->onPositionChanged =  ::lime::app::_Event_Single_Void_obj::__alloc( HX_CTX );
HXLINE(  36)		this->onTimeChanged =  ::lime::app::_Event_haxe_Int64_Void_obj::__alloc( HX_CTX );
HXLINE(  33)		this->onEncounteredError =  ::lime::app::_Event_String_Void_obj::__alloc( HX_CTX );
HXLINE(  30)		this->onEndReached =  ::lime::app::_Event_Void_Void_obj::__alloc( HX_CTX );
HXLINE(  27)		this->onPaused =  ::lime::app::_Event_Void_Void_obj::__alloc( HX_CTX );
HXLINE(  24)		this->onStopped =  ::lime::app::_Event_Void_Void_obj::__alloc( HX_CTX );
HXLINE(  21)		this->onPlaying =  ::lime::app::_Event_Void_Void_obj::__alloc( HX_CTX );
HXLINE(  18)		this->onOpening =  ::lime::app::_Event_Void_Void_obj::__alloc( HX_CTX );
HXLINE(  15)		this->members = ::Array_obj< ::Dynamic>::__new(0);
HXLINE( 127)		this->_dispatchOpening = this->onOpening->dispatch_dyn();
HXLINE( 128)		this->_dispatchPlaying = this->onPlaying->dispatch_dyn();
HXLINE( 129)		this->_dispatchStopped = this->onStopped->dispatch_dyn();
HXLINE( 130)		this->_dispatchPaused = this->onPaused->dispatch_dyn();
HXLINE( 131)		this->_dispatchEndReached = this->onEndReached->dispatch_dyn();
HXLINE( 132)		this->_dispatchEncounteredError = this->onEncounteredError->dispatch_dyn();
HXLINE( 133)		this->_dispatchTimeChanged = this->onTimeChanged->dispatch_dyn();
HXLINE( 134)		this->_dispatchPositionChanged = this->onPositionChanged->dispatch_dyn();
HXLINE( 135)		this->_dispatchLengthChanged = this->onLengthChanged->dispatch_dyn();
            	}

Dynamic AudioGroup_obj::__CreateEmpty() { return new AudioGroup_obj; }

void *AudioGroup_obj::_hx_vtable = 0;

Dynamic AudioGroup_obj::__Create(::hx::DynamicArray inArgs)
{
	::hx::ObjectPtr< AudioGroup_obj > _hx_result = new AudioGroup_obj();
	_hx_result->__construct();
	return _hx_result;
}

bool AudioGroup_obj::_hx_isInstanceOf(int inClassId) {
	return inClassId==(int)0x00000001 || inClassId==(int)0x5602baf2;
}

void AudioGroup_obj::add( ::hxvlc::openfl::Audio audio){
            	HX_STACKFRAME(&_hx_pos_c45750b9e975401e_145_add)
HXDLIN( 145)		bool _hx_tmp;
HXDLIN( 145)		if (::hx::IsNotNull( audio )) {
HXDLIN( 145)			_hx_tmp = !(this->members->contains(audio));
            		}
            		else {
HXDLIN( 145)			_hx_tmp = false;
            		}
HXDLIN( 145)		if (_hx_tmp) {
HXLINE( 147)			this->members->push(audio);
HXLINE( 149)			audio->set_volume((this->_volume * audio->groupVolume));
HXLINE( 151)			if ((this->members->length == 1)) {
HXLINE( 152)				this->updateFirstMemberListeners();
            			}
            		}
            	}


HX_DEFINE_DYNAMIC_FUNC1(AudioGroup_obj,add,(void))

void AudioGroup_obj::remove( ::hxvlc::openfl::Audio audio){
            	HX_STACKFRAME(&_hx_pos_c45750b9e975401e_163_remove)
HXDLIN( 163)		if (this->members->remove(audio)) {
HXLINE( 165)			this->updateFirstMemberListeners();
            		}
            	}


HX_DEFINE_DYNAMIC_FUNC1(AudioGroup_obj,remove,(void))

bool AudioGroup_obj::addTrack(::String location,::Array< ::String > options,::hx::Null< int >  __o_id){
            		int id = __o_id.Default(9999);
            	HX_GC_STACKFRAME(&_hx_pos_c45750b9e975401e_178_addTrack)
HXLINE( 179)		if ((id <= 0)) {
HXLINE( 180)			return false;
            		}
HXLINE( 182)		if ((this->members->length < id)) {
HXLINE( 184)			 ::hxvlc::openfl::Audio audio =  ::hxvlc::openfl::Audio_obj::__alloc( HX_CTX );
HXLINE( 186)			if (audio->load(location,options)) {
HXLINE( 188)				this->add(audio);
HXLINE( 190)				return true;
            			}
HXLINE( 193)			audio->dispose();
HXLINE( 195)			return false;
            		}
            		else {
HXLINE( 199)			this->members->__get((id - 1)).StaticCast<  ::hxvlc::openfl::Audio >()->releaseMedia();
HXLINE( 200)			bool success = this->members->__get((id - 1)).StaticCast<  ::hxvlc::openfl::Audio >()->load(location,options);
HXLINE( 202)			if (success) {
HXLINE( 203)				this->members->__get((id - 1)).StaticCast<  ::hxvlc::openfl::Audio >()->set_volume((this->_volume * this->members->__get((id - 1)).StaticCast<  ::hxvlc::openfl::Audio >()->groupVolume));
            			}
HXLINE( 205)			return success;
            		}
HXLINE( 182)		return false;
            	}


HX_DEFINE_DYNAMIC_FUNC3(AudioGroup_obj,addTrack,return )

void AudioGroup_obj::addTrackAsync(::String location,::Array< ::String > options,::hx::Null< int >  __o_id, ::Dynamic onComplete){
            		int id = __o_id.Default(9999);
            	HX_GC_STACKFRAME(&_hx_pos_c45750b9e975401e_218_addTrackAsync)
HXDLIN( 218)		 ::hxvlc::openfl::AudioGroup _gthis = ::hx::ObjectPtr<OBJ_>(this);
HXLINE( 219)		if ((id <= 0)) {
HXLINE( 221)			if (::hx::IsNotNull( onComplete )) {
HXLINE( 222)				onComplete(false);
            			}
HXLINE( 224)			return;
            		}
HXLINE( 227)		if ((this->members->length < id)) {
            			HX_BEGIN_LOCAL_FUNC_S3(::hx::LocalFunc,_hx_Closure_0, ::hxvlc::openfl::AudioGroup,_gthis, ::Dynamic,onComplete, ::hxvlc::openfl::Audio,audio) HXARGC(0)
            			void _hx_run(){
            				HX_GC_STACKFRAME(&_hx_pos_c45750b9e975401e_232_addTrackAsync)
HXLINE( 233)				_gthis->add(audio);
HXLINE( 235)				if (::hx::IsNotNull( onComplete )) {
HXLINE( 236)					onComplete(true);
            				}
            			}
            			HX_END_LOCAL_FUNC0((void))

            			HX_BEGIN_LOCAL_FUNC_S2(::hx::LocalFunc,_hx_Closure_1, ::Dynamic,onComplete, ::hxvlc::openfl::Audio,audio) HXARGC(1)
            			void _hx_run(::String error){
            				HX_GC_STACKFRAME(&_hx_pos_c45750b9e975401e_238_addTrackAsync)
HXLINE( 239)				audio->dispose();
HXLINE( 241)				if (::hx::IsNotNull( onComplete )) {
HXLINE( 242)					onComplete(false);
            				}
            			}
            			HX_END_LOCAL_FUNC1((void))

HXLINE( 229)			 ::hxvlc::openfl::Audio audio =  ::hxvlc::openfl::Audio_obj::__alloc( HX_CTX );
HXLINE( 231)			audio->loadAsync(location,options, ::Dynamic(new _hx_Closure_0(_gthis,onComplete,audio)), ::Dynamic(new _hx_Closure_1(onComplete,audio)));
            		}
            		else {
HXLINE( 247)			 ::hxvlc::openfl::Audio member = this->members->__get((id - 1)).StaticCast<  ::hxvlc::openfl::Audio >();
HXLINE( 249)			if (::hx::IsNotNull( member )) {
            				HX_BEGIN_LOCAL_FUNC_S3(::hx::LocalFunc,_hx_Closure_2, ::hxvlc::openfl::AudioGroup,_gthis, ::Dynamic,onComplete, ::hxvlc::openfl::Audio,member) HXARGC(0)
            				void _hx_run(){
            					HX_GC_STACKFRAME(&_hx_pos_c45750b9e975401e_254_addTrackAsync)
HXLINE( 255)					if (_gthis->members->contains(member)) {
HXLINE( 256)						member->set_volume((_gthis->_volume * member->groupVolume));
            					}
HXLINE( 258)					if (::hx::IsNotNull( onComplete )) {
HXLINE( 259)						onComplete(true);
            					}
            				}
            				HX_END_LOCAL_FUNC0((void))

            				HX_BEGIN_LOCAL_FUNC_S1(::hx::LocalFunc,_hx_Closure_3, ::Dynamic,onComplete) HXARGC(1)
            				void _hx_run(::String error){
            					HX_GC_STACKFRAME(&_hx_pos_c45750b9e975401e_262_addTrackAsync)
HXLINE( 262)					if (::hx::IsNotNull( onComplete )) {
HXLINE( 263)						onComplete(false);
            					}
            				}
            				HX_END_LOCAL_FUNC1((void))

HXLINE( 251)				member->releaseMedia();
HXLINE( 253)				member->loadAsync(location,options, ::Dynamic(new _hx_Closure_2(_gthis,onComplete,member)), ::Dynamic(new _hx_Closure_3(onComplete)));
            			}
            			else {
HXLINE( 268)				if (::hx::IsNotNull( onComplete )) {
HXLINE( 269)					onComplete(false);
            				}
            			}
            		}
            	}


HX_DEFINE_DYNAMIC_FUNC4(AudioGroup_obj,addTrackAsync,(void))

void AudioGroup_obj::releaseMedia(int id){
            	HX_STACKFRAME(&_hx_pos_c45750b9e975401e_275_releaseMedia)
HXLINE( 276)		bool _hx_tmp;
HXDLIN( 276)		if ((id > 0)) {
HXLINE( 276)			_hx_tmp = (id > this->members->length);
            		}
            		else {
HXLINE( 276)			_hx_tmp = true;
            		}
HXDLIN( 276)		if (_hx_tmp) {
HXLINE( 277)			return;
            		}
HXLINE( 279)		this->members->__get((id - 1)).StaticCast<  ::hxvlc::openfl::Audio >()->releaseMedia();
            	}


HX_DEFINE_DYNAMIC_FUNC1(AudioGroup_obj,releaseMedia,(void))

void AudioGroup_obj::play(::hx::Null< int >  __o_delay){
            		int delay = __o_delay.Default(50);
            	HX_STACKFRAME(&_hx_pos_c45750b9e975401e_288_play)
HXLINE( 289)		Float syncTime = (::lime::_hx_system::System_obj::getTimerNano() + delay);
HXLINE( 291)		{
HXLINE( 291)			int _g = 0;
HXDLIN( 291)			::Array< ::Dynamic> _g1 = this->members;
HXDLIN( 291)			while((_g < _g1->length)){
HXLINE( 291)				 ::hxvlc::openfl::Audio audio = _g1->__get(_g).StaticCast<  ::hxvlc::openfl::Audio >();
HXDLIN( 291)				_g = (_g + 1);
HXLINE( 293)				audio->syncStartTime = syncTime;
HXLINE( 294)				audio->play();
            			}
            		}
            	}


HX_DEFINE_DYNAMIC_FUNC1(AudioGroup_obj,play,(void))

void AudioGroup_obj::pause(){
            	HX_STACKFRAME(&_hx_pos_c45750b9e975401e_303_pause)
HXDLIN( 303)		int _g = 0;
HXDLIN( 303)		::Array< ::Dynamic> _g1 = this->members;
HXDLIN( 303)		while((_g < _g1->length)){
HXDLIN( 303)			 ::hxvlc::openfl::Audio audio = _g1->__get(_g).StaticCast<  ::hxvlc::openfl::Audio >();
HXDLIN( 303)			_g = (_g + 1);
HXLINE( 304)			audio->pause();
            		}
            	}


HX_DEFINE_DYNAMIC_FUNC0(AudioGroup_obj,pause,(void))

void AudioGroup_obj::resume(){
            	HX_STACKFRAME(&_hx_pos_c45750b9e975401e_312_resume)
HXDLIN( 312)		int _g = 0;
HXDLIN( 312)		::Array< ::Dynamic> _g1 = this->members;
HXDLIN( 312)		while((_g < _g1->length)){
HXDLIN( 312)			 ::hxvlc::openfl::Audio audio = _g1->__get(_g).StaticCast<  ::hxvlc::openfl::Audio >();
HXDLIN( 312)			_g = (_g + 1);
HXLINE( 313)			audio->resume();
            		}
            	}


HX_DEFINE_DYNAMIC_FUNC0(AudioGroup_obj,resume,(void))

void AudioGroup_obj::stop(){
            	HX_STACKFRAME(&_hx_pos_c45750b9e975401e_320_stop)
HXLINE( 321)		if (!(this->autoDestroy)) {
HXLINE( 323)			{
HXLINE( 323)				int _g = 0;
HXDLIN( 323)				::Array< ::Dynamic> _g1 = this->members;
HXDLIN( 323)				while((_g < _g1->length)){
HXLINE( 323)					 ::hxvlc::openfl::Audio audio = _g1->__get(_g).StaticCast<  ::hxvlc::openfl::Audio >();
HXDLIN( 323)					_g = (_g + 1);
HXLINE( 325)					audio->syncStartTime = ( (Float)(-1) );
HXLINE( 326)					audio->stop();
            				}
            			}
HXLINE( 329)			return;
            		}
HXLINE( 332)		{
HXLINE( 332)			int _g2 = 0;
HXDLIN( 332)			::Array< ::Dynamic> _g3 = this->members;
HXDLIN( 332)			while((_g2 < _g3->length)){
HXLINE( 332)				 ::hxvlc::openfl::Audio audio1 = _g3->__get(_g2).StaticCast<  ::hxvlc::openfl::Audio >();
HXDLIN( 332)				_g2 = (_g2 + 1);
HXLINE( 334)				audio1->syncStartTime = ( (Float)(-1) );
HXLINE( 335)				audio1->stop();
            			}
            		}
HXLINE( 338)		this->detachFirstMemberListeners();
HXLINE( 339)		this->_firstMember = null();
HXLINE( 341)		{
HXLINE( 341)			int _g4 = 0;
HXDLIN( 341)			::Array< ::Dynamic> _g5 = this->members;
HXDLIN( 341)			while((_g4 < _g5->length)){
HXLINE( 341)				 ::hxvlc::openfl::Audio audio2 = _g5->__get(_g4).StaticCast<  ::hxvlc::openfl::Audio >();
HXDLIN( 341)				_g4 = (_g4 + 1);
HXLINE( 342)				audio2->dispose();
            			}
            		}
HXLINE( 344)		this->members->resize(0);
            	}


HX_DEFINE_DYNAMIC_FUNC0(AudioGroup_obj,stop,(void))

void AudioGroup_obj::setTime(::cpp::Int64 time){
            	HX_STACKFRAME(&_hx_pos_c45750b9e975401e_354_setTime)
HXDLIN( 354)		int _g = 0;
HXDLIN( 354)		::Array< ::Dynamic> _g1 = this->members;
HXDLIN( 354)		while((_g < _g1->length)){
HXDLIN( 354)			 ::hxvlc::openfl::Audio audio = _g1->__get(_g).StaticCast<  ::hxvlc::openfl::Audio >();
HXDLIN( 354)			_g = (_g + 1);
HXLINE( 355)			audio->set_time(time);
            		}
            	}


HX_DEFINE_DYNAMIC_FUNC1(AudioGroup_obj,setTime,(void))

void AudioGroup_obj::dispose(){
            	HX_STACKFRAME(&_hx_pos_c45750b9e975401e_362_dispose)
HXLINE( 363)		this->detachFirstMemberListeners();
HXLINE( 364)		this->_firstMember = null();
HXLINE( 366)		{
HXLINE( 366)			int _g = 0;
HXDLIN( 366)			::Array< ::Dynamic> _g1 = this->members;
HXDLIN( 366)			while((_g < _g1->length)){
HXLINE( 366)				 ::hxvlc::openfl::Audio audio = _g1->__get(_g).StaticCast<  ::hxvlc::openfl::Audio >();
HXDLIN( 366)				_g = (_g + 1);
HXLINE( 367)				audio->dispose();
            			}
            		}
HXLINE( 369)		this->members->resize(0);
            	}


HX_DEFINE_DYNAMIC_FUNC0(AudioGroup_obj,dispose,(void))

::cpp::Int64 AudioGroup_obj::get_length(){
            	HX_STACKFRAME(&_hx_pos_c45750b9e975401e_375_get_length)
HXDLIN( 375)		if ((this->members->length > 0)) {
HXDLIN( 375)			return this->members->__get(0).StaticCast<  ::hxvlc::openfl::Audio >()->get_length();
            		}
            		else {
HXDLIN( 375)			return ( (::cpp::Int64)(-1) );
            		}
HXDLIN( 375)		return null();
            	}


HX_DEFINE_DYNAMIC_FUNC0(AudioGroup_obj,get_length,return )

::cpp::Int64 AudioGroup_obj::get_duration(){
            	HX_STACKFRAME(&_hx_pos_c45750b9e975401e_381_get_duration)
HXDLIN( 381)		if ((this->members->length > 0)) {
HXDLIN( 381)			return this->members->__get(0).StaticCast<  ::hxvlc::openfl::Audio >()->get_duration();
            		}
            		else {
HXDLIN( 381)			return ( (::cpp::Int64)(-1) );
            		}
HXDLIN( 381)		return null();
            	}


HX_DEFINE_DYNAMIC_FUNC0(AudioGroup_obj,get_duration,return )

::cpp::Int64 AudioGroup_obj::get_time(){
            	HX_STACKFRAME(&_hx_pos_c45750b9e975401e_387_get_time)
HXDLIN( 387)		if ((this->members->length > 0)) {
HXDLIN( 387)			return this->members->__get(0).StaticCast<  ::hxvlc::openfl::Audio >()->get_time();
            		}
            		else {
HXDLIN( 387)			return ( (::cpp::Int64)(-1) );
            		}
HXDLIN( 387)		return null();
            	}


HX_DEFINE_DYNAMIC_FUNC0(AudioGroup_obj,get_time,return )

::cpp::Int64 AudioGroup_obj::set_time(::cpp::Int64 value){
            	HX_STACKFRAME(&_hx_pos_c45750b9e975401e_392_set_time)
HXLINE( 393)		{
HXLINE( 393)			int _g = 0;
HXDLIN( 393)			::Array< ::Dynamic> _g1 = this->members;
HXDLIN( 393)			while((_g < _g1->length)){
HXLINE( 393)				 ::hxvlc::openfl::Audio audio = _g1->__get(_g).StaticCast<  ::hxvlc::openfl::Audio >();
HXDLIN( 393)				_g = (_g + 1);
HXLINE( 394)				audio->set_time(value);
            			}
            		}
HXLINE( 396)		return value;
            	}


HX_DEFINE_DYNAMIC_FUNC1(AudioGroup_obj,set_time,return )

float AudioGroup_obj::get_position(){
            	HX_STACKFRAME(&_hx_pos_c45750b9e975401e_402_get_position)
HXDLIN( 402)		if ((this->members->length > 0)) {
HXDLIN( 402)			return this->members->__get(0).StaticCast<  ::hxvlc::openfl::Audio >()->get_position();
            		}
            		else {
HXDLIN( 402)			return ( (float)(0) );
            		}
HXDLIN( 402)		return null();
            	}


HX_DEFINE_DYNAMIC_FUNC0(AudioGroup_obj,get_position,return )

float AudioGroup_obj::set_position(float value){
            	HX_STACKFRAME(&_hx_pos_c45750b9e975401e_407_set_position)
HXLINE( 408)		{
HXLINE( 408)			int _g = 0;
HXDLIN( 408)			::Array< ::Dynamic> _g1 = this->members;
HXDLIN( 408)			while((_g < _g1->length)){
HXLINE( 408)				 ::hxvlc::openfl::Audio audio = _g1->__get(_g).StaticCast<  ::hxvlc::openfl::Audio >();
HXDLIN( 408)				_g = (_g + 1);
HXLINE( 409)				audio->set_position(value);
            			}
            		}
HXLINE( 411)		return value;
            	}


HX_DEFINE_DYNAMIC_FUNC1(AudioGroup_obj,set_position,return )

float AudioGroup_obj::get_volume(){
            	HX_STACKFRAME(&_hx_pos_c45750b9e975401e_417_get_volume)
HXDLIN( 417)		return this->_volume;
            	}


HX_DEFINE_DYNAMIC_FUNC0(AudioGroup_obj,get_volume,return )

float AudioGroup_obj::set_volume(float value){
            	HX_STACKFRAME(&_hx_pos_c45750b9e975401e_422_set_volume)
HXLINE( 423)		this->_volume = value;
HXLINE( 425)		{
HXLINE( 425)			int _g = 0;
HXDLIN( 425)			::Array< ::Dynamic> _g1 = this->members;
HXDLIN( 425)			while((_g < _g1->length)){
HXLINE( 425)				 ::hxvlc::openfl::Audio audio = _g1->__get(_g).StaticCast<  ::hxvlc::openfl::Audio >();
HXDLIN( 425)				_g = (_g + 1);
HXLINE( 426)				audio->set_volume((value * audio->groupVolume));
            			}
            		}
HXLINE( 428)		return value;
            	}


HX_DEFINE_DYNAMIC_FUNC1(AudioGroup_obj,set_volume,return )

float AudioGroup_obj::get_rate(){
            	HX_STACKFRAME(&_hx_pos_c45750b9e975401e_434_get_rate)
HXDLIN( 434)		if ((this->members->length > 0)) {
HXDLIN( 434)			return this->members->__get(0).StaticCast<  ::hxvlc::openfl::Audio >()->get_rate();
            		}
            		else {
HXDLIN( 434)			return ( (float)(1) );
            		}
HXDLIN( 434)		return null();
            	}


HX_DEFINE_DYNAMIC_FUNC0(AudioGroup_obj,get_rate,return )

float AudioGroup_obj::set_rate(float value){
            	HX_STACKFRAME(&_hx_pos_c45750b9e975401e_439_set_rate)
HXLINE( 440)		{
HXLINE( 440)			int _g = 0;
HXDLIN( 440)			::Array< ::Dynamic> _g1 = this->members;
HXDLIN( 440)			while((_g < _g1->length)){
HXLINE( 440)				 ::hxvlc::openfl::Audio audio = _g1->__get(_g).StaticCast<  ::hxvlc::openfl::Audio >();
HXDLIN( 440)				_g = (_g + 1);
HXLINE( 441)				audio->set_rate(value);
            			}
            		}
HXLINE( 443)		return value;
            	}


HX_DEFINE_DYNAMIC_FUNC1(AudioGroup_obj,set_rate,return )

bool AudioGroup_obj::get_isPlaying(){
            	HX_STACKFRAME(&_hx_pos_c45750b9e975401e_448_get_isPlaying)
HXLINE( 449)		{
HXLINE( 449)			int _g = 0;
HXDLIN( 449)			::Array< ::Dynamic> _g1 = this->members;
HXDLIN( 449)			while((_g < _g1->length)){
HXLINE( 449)				 ::hxvlc::openfl::Audio audio = _g1->__get(_g).StaticCast<  ::hxvlc::openfl::Audio >();
HXDLIN( 449)				_g = (_g + 1);
HXLINE( 451)				if (audio->get_isPlaying()) {
HXLINE( 452)					return true;
            				}
            			}
            		}
HXLINE( 455)		return false;
            	}


HX_DEFINE_DYNAMIC_FUNC0(AudioGroup_obj,get_isPlaying,return )

void AudioGroup_obj::updateFirstMemberListeners(){
            	HX_STACKFRAME(&_hx_pos_c45750b9e975401e_460_updateFirstMemberListeners)
HXLINE( 461)		this->detachFirstMemberListeners();
HXLINE( 463)		 ::hxvlc::openfl::Audio _hx_tmp;
HXDLIN( 463)		if ((this->members->length > 0)) {
HXLINE( 463)			_hx_tmp = this->members->__get(0).StaticCast<  ::hxvlc::openfl::Audio >();
            		}
            		else {
HXLINE( 463)			_hx_tmp = null();
            		}
HXDLIN( 463)		this->_firstMember = _hx_tmp;
HXLINE( 465)		this->attachFirstMemberListeners();
            	}


HX_DEFINE_DYNAMIC_FUNC0(AudioGroup_obj,updateFirstMemberListeners,(void))

void AudioGroup_obj::detachFirstMemberListeners(){
            	HX_STACKFRAME(&_hx_pos_c45750b9e975401e_470_detachFirstMemberListeners)
HXLINE( 471)		if (::hx::IsNull( this->_firstMember )) {
HXLINE( 472)			return;
            		}
HXLINE( 474)		this->_firstMember->onOpening->remove(this->_dispatchOpening);
HXLINE( 475)		this->_firstMember->onPlaying->remove(this->_dispatchPlaying);
HXLINE( 476)		this->_firstMember->onStopped->remove(this->_dispatchStopped);
HXLINE( 477)		this->_firstMember->onPaused->remove(this->_dispatchPaused);
HXLINE( 478)		this->_firstMember->onEndReached->remove(this->_dispatchEndReached);
HXLINE( 479)		this->_firstMember->onEncounteredError->remove(this->_dispatchEncounteredError);
HXLINE( 480)		this->_firstMember->onTimeChanged->remove(this->_dispatchTimeChanged);
HXLINE( 481)		this->_firstMember->onPositionChanged->remove(this->_dispatchPositionChanged);
HXLINE( 482)		this->_firstMember->onLengthChanged->remove(this->_dispatchLengthChanged);
            	}


HX_DEFINE_DYNAMIC_FUNC0(AudioGroup_obj,detachFirstMemberListeners,(void))

void AudioGroup_obj::attachFirstMemberListeners(){
            	HX_STACKFRAME(&_hx_pos_c45750b9e975401e_487_attachFirstMemberListeners)
HXLINE( 488)		if (::hx::IsNull( this->_firstMember )) {
HXLINE( 489)			return;
            		}
HXLINE( 491)		this->_firstMember->onOpening->add(this->_dispatchOpening,null(),null());
HXLINE( 492)		this->_firstMember->onPlaying->add(this->_dispatchPlaying,null(),null());
HXLINE( 493)		this->_firstMember->onStopped->add(this->_dispatchStopped,null(),null());
HXLINE( 494)		this->_firstMember->onPaused->add(this->_dispatchPaused,null(),null());
HXLINE( 495)		this->_firstMember->onEndReached->add(this->_dispatchEndReached,null(),null());
HXLINE( 496)		this->_firstMember->onEncounteredError->add(this->_dispatchEncounteredError,null(),null());
HXLINE( 497)		this->_firstMember->onTimeChanged->add(this->_dispatchTimeChanged,null(),null());
HXLINE( 498)		this->_firstMember->onPositionChanged->add(this->_dispatchPositionChanged,null(),null());
HXLINE( 499)		this->_firstMember->onLengthChanged->add(this->_dispatchLengthChanged,null(),null());
            	}


HX_DEFINE_DYNAMIC_FUNC0(AudioGroup_obj,attachFirstMemberListeners,(void))


::hx::ObjectPtr< AudioGroup_obj > AudioGroup_obj::__new() {
	::hx::ObjectPtr< AudioGroup_obj > __this = new AudioGroup_obj();
	__this->__construct();
	return __this;
}

::hx::ObjectPtr< AudioGroup_obj > AudioGroup_obj::__alloc(::hx::Ctx *_hx_ctx) {
	AudioGroup_obj *__this = (AudioGroup_obj*)(::hx::Ctx::alloc(_hx_ctx, sizeof(AudioGroup_obj), true, "hxvlc.openfl.AudioGroup"));
	*(void **)__this = AudioGroup_obj::_hx_vtable;
	__this->__construct();
	return __this;
}

AudioGroup_obj::AudioGroup_obj()
{
}

void AudioGroup_obj::__Mark(HX_MARK_PARAMS)
{
	HX_MARK_BEGIN_CLASS(AudioGroup);
	HX_MARK_MEMBER_NAME(members,"members");
	HX_MARK_MEMBER_NAME(onOpening,"onOpening");
	HX_MARK_MEMBER_NAME(onPlaying,"onPlaying");
	HX_MARK_MEMBER_NAME(onStopped,"onStopped");
	HX_MARK_MEMBER_NAME(onPaused,"onPaused");
	HX_MARK_MEMBER_NAME(onEndReached,"onEndReached");
	HX_MARK_MEMBER_NAME(onEncounteredError,"onEncounteredError");
	HX_MARK_MEMBER_NAME(onTimeChanged,"onTimeChanged");
	HX_MARK_MEMBER_NAME(onPositionChanged,"onPositionChanged");
	HX_MARK_MEMBER_NAME(onLengthChanged,"onLengthChanged");
	HX_MARK_MEMBER_NAME(autoDestroy,"autoDestroy");
	HX_MARK_MEMBER_NAME(_firstMember,"_firstMember");
	HX_MARK_MEMBER_NAME(_volume,"_volume");
	HX_MARK_MEMBER_NAME(_dispatchOpening,"_dispatchOpening");
	HX_MARK_MEMBER_NAME(_dispatchPlaying,"_dispatchPlaying");
	HX_MARK_MEMBER_NAME(_dispatchStopped,"_dispatchStopped");
	HX_MARK_MEMBER_NAME(_dispatchPaused,"_dispatchPaused");
	HX_MARK_MEMBER_NAME(_dispatchEndReached,"_dispatchEndReached");
	HX_MARK_MEMBER_NAME(_dispatchEncounteredError,"_dispatchEncounteredError");
	HX_MARK_MEMBER_NAME(_dispatchTimeChanged,"_dispatchTimeChanged");
	HX_MARK_MEMBER_NAME(_dispatchPositionChanged,"_dispatchPositionChanged");
	HX_MARK_MEMBER_NAME(_dispatchLengthChanged,"_dispatchLengthChanged");
	HX_MARK_END_CLASS();
}

void AudioGroup_obj::__Visit(HX_VISIT_PARAMS)
{
	HX_VISIT_MEMBER_NAME(members,"members");
	HX_VISIT_MEMBER_NAME(onOpening,"onOpening");
	HX_VISIT_MEMBER_NAME(onPlaying,"onPlaying");
	HX_VISIT_MEMBER_NAME(onStopped,"onStopped");
	HX_VISIT_MEMBER_NAME(onPaused,"onPaused");
	HX_VISIT_MEMBER_NAME(onEndReached,"onEndReached");
	HX_VISIT_MEMBER_NAME(onEncounteredError,"onEncounteredError");
	HX_VISIT_MEMBER_NAME(onTimeChanged,"onTimeChanged");
	HX_VISIT_MEMBER_NAME(onPositionChanged,"onPositionChanged");
	HX_VISIT_MEMBER_NAME(onLengthChanged,"onLengthChanged");
	HX_VISIT_MEMBER_NAME(autoDestroy,"autoDestroy");
	HX_VISIT_MEMBER_NAME(_firstMember,"_firstMember");
	HX_VISIT_MEMBER_NAME(_volume,"_volume");
	HX_VISIT_MEMBER_NAME(_dispatchOpening,"_dispatchOpening");
	HX_VISIT_MEMBER_NAME(_dispatchPlaying,"_dispatchPlaying");
	HX_VISIT_MEMBER_NAME(_dispatchStopped,"_dispatchStopped");
	HX_VISIT_MEMBER_NAME(_dispatchPaused,"_dispatchPaused");
	HX_VISIT_MEMBER_NAME(_dispatchEndReached,"_dispatchEndReached");
	HX_VISIT_MEMBER_NAME(_dispatchEncounteredError,"_dispatchEncounteredError");
	HX_VISIT_MEMBER_NAME(_dispatchTimeChanged,"_dispatchTimeChanged");
	HX_VISIT_MEMBER_NAME(_dispatchPositionChanged,"_dispatchPositionChanged");
	HX_VISIT_MEMBER_NAME(_dispatchLengthChanged,"_dispatchLengthChanged");
}

::hx::Val AudioGroup_obj::__Field(const ::String &inName,::hx::PropertyAccess inCallProp)
{
	switch(inName.length) {
	case 3:
		if (HX_FIELD_EQ(inName,"add") ) { return ::hx::Val( add_dyn() ); }
		break;
	case 4:
		if (HX_FIELD_EQ(inName,"time") ) { if (inCallProp == ::hx::paccAlways) return ::hx::Val( get_time() ); }
		if (HX_FIELD_EQ(inName,"rate") ) { if (inCallProp == ::hx::paccAlways) return ::hx::Val( get_rate() ); }
		if (HX_FIELD_EQ(inName,"play") ) { return ::hx::Val( play_dyn() ); }
		if (HX_FIELD_EQ(inName,"stop") ) { return ::hx::Val( stop_dyn() ); }
		break;
	case 5:
		if (HX_FIELD_EQ(inName,"pause") ) { return ::hx::Val( pause_dyn() ); }
		break;
	case 6:
		if (HX_FIELD_EQ(inName,"length") ) { if (inCallProp == ::hx::paccAlways) return ::hx::Val( get_length() ); }
		if (HX_FIELD_EQ(inName,"volume") ) { if (inCallProp == ::hx::paccAlways) return ::hx::Val( get_volume() ); }
		if (HX_FIELD_EQ(inName,"remove") ) { return ::hx::Val( remove_dyn() ); }
		if (HX_FIELD_EQ(inName,"resume") ) { return ::hx::Val( resume_dyn() ); }
		break;
	case 7:
		if (HX_FIELD_EQ(inName,"members") ) { return ::hx::Val( members ); }
		if (HX_FIELD_EQ(inName,"_volume") ) { return ::hx::Val( _volume ); }
		if (HX_FIELD_EQ(inName,"setTime") ) { return ::hx::Val( setTime_dyn() ); }
		if (HX_FIELD_EQ(inName,"dispose") ) { return ::hx::Val( dispose_dyn() ); }
		break;
	case 8:
		if (HX_FIELD_EQ(inName,"onPaused") ) { return ::hx::Val( onPaused ); }
		if (HX_FIELD_EQ(inName,"duration") ) { if (inCallProp == ::hx::paccAlways) return ::hx::Val( get_duration() ); }
		if (HX_FIELD_EQ(inName,"position") ) { if (inCallProp == ::hx::paccAlways) return ::hx::Val( get_position() ); }
		if (HX_FIELD_EQ(inName,"addTrack") ) { return ::hx::Val( addTrack_dyn() ); }
		if (HX_FIELD_EQ(inName,"get_time") ) { return ::hx::Val( get_time_dyn() ); }
		if (HX_FIELD_EQ(inName,"set_time") ) { return ::hx::Val( set_time_dyn() ); }
		if (HX_FIELD_EQ(inName,"get_rate") ) { return ::hx::Val( get_rate_dyn() ); }
		if (HX_FIELD_EQ(inName,"set_rate") ) { return ::hx::Val( set_rate_dyn() ); }
		break;
	case 9:
		if (HX_FIELD_EQ(inName,"onOpening") ) { return ::hx::Val( onOpening ); }
		if (HX_FIELD_EQ(inName,"onPlaying") ) { return ::hx::Val( onPlaying ); }
		if (HX_FIELD_EQ(inName,"onStopped") ) { return ::hx::Val( onStopped ); }
		if (HX_FIELD_EQ(inName,"isPlaying") ) { if (inCallProp == ::hx::paccAlways) return ::hx::Val( get_isPlaying() ); }
		break;
	case 10:
		if (HX_FIELD_EQ(inName,"get_length") ) { return ::hx::Val( get_length_dyn() ); }
		if (HX_FIELD_EQ(inName,"get_volume") ) { return ::hx::Val( get_volume_dyn() ); }
		if (HX_FIELD_EQ(inName,"set_volume") ) { return ::hx::Val( set_volume_dyn() ); }
		break;
	case 11:
		if (HX_FIELD_EQ(inName,"autoDestroy") ) { return ::hx::Val( autoDestroy ); }
		break;
	case 12:
		if (HX_FIELD_EQ(inName,"onEndReached") ) { return ::hx::Val( onEndReached ); }
		if (HX_FIELD_EQ(inName,"_firstMember") ) { return ::hx::Val( _firstMember ); }
		if (HX_FIELD_EQ(inName,"releaseMedia") ) { return ::hx::Val( releaseMedia_dyn() ); }
		if (HX_FIELD_EQ(inName,"get_duration") ) { return ::hx::Val( get_duration_dyn() ); }
		if (HX_FIELD_EQ(inName,"get_position") ) { return ::hx::Val( get_position_dyn() ); }
		if (HX_FIELD_EQ(inName,"set_position") ) { return ::hx::Val( set_position_dyn() ); }
		break;
	case 13:
		if (HX_FIELD_EQ(inName,"onTimeChanged") ) { return ::hx::Val( onTimeChanged ); }
		if (HX_FIELD_EQ(inName,"addTrackAsync") ) { return ::hx::Val( addTrackAsync_dyn() ); }
		if (HX_FIELD_EQ(inName,"get_isPlaying") ) { return ::hx::Val( get_isPlaying_dyn() ); }
		break;
	case 15:
		if (HX_FIELD_EQ(inName,"onLengthChanged") ) { return ::hx::Val( onLengthChanged ); }
		if (HX_FIELD_EQ(inName,"_dispatchPaused") ) { return ::hx::Val( _dispatchPaused ); }
		break;
	case 16:
		if (HX_FIELD_EQ(inName,"_dispatchOpening") ) { return ::hx::Val( _dispatchOpening ); }
		if (HX_FIELD_EQ(inName,"_dispatchPlaying") ) { return ::hx::Val( _dispatchPlaying ); }
		if (HX_FIELD_EQ(inName,"_dispatchStopped") ) { return ::hx::Val( _dispatchStopped ); }
		break;
	case 17:
		if (HX_FIELD_EQ(inName,"onPositionChanged") ) { return ::hx::Val( onPositionChanged ); }
		break;
	case 18:
		if (HX_FIELD_EQ(inName,"onEncounteredError") ) { return ::hx::Val( onEncounteredError ); }
		break;
	case 19:
		if (HX_FIELD_EQ(inName,"_dispatchEndReached") ) { return ::hx::Val( _dispatchEndReached ); }
		break;
	case 20:
		if (HX_FIELD_EQ(inName,"_dispatchTimeChanged") ) { return ::hx::Val( _dispatchTimeChanged ); }
		break;
	case 22:
		if (HX_FIELD_EQ(inName,"_dispatchLengthChanged") ) { return ::hx::Val( _dispatchLengthChanged ); }
		break;
	case 24:
		if (HX_FIELD_EQ(inName,"_dispatchPositionChanged") ) { return ::hx::Val( _dispatchPositionChanged ); }
		break;
	case 25:
		if (HX_FIELD_EQ(inName,"_dispatchEncounteredError") ) { return ::hx::Val( _dispatchEncounteredError ); }
		break;
	case 26:
		if (HX_FIELD_EQ(inName,"updateFirstMemberListeners") ) { return ::hx::Val( updateFirstMemberListeners_dyn() ); }
		if (HX_FIELD_EQ(inName,"detachFirstMemberListeners") ) { return ::hx::Val( detachFirstMemberListeners_dyn() ); }
		if (HX_FIELD_EQ(inName,"attachFirstMemberListeners") ) { return ::hx::Val( attachFirstMemberListeners_dyn() ); }
	}
	return super::__Field(inName,inCallProp);
}

::hx::Val AudioGroup_obj::__SetField(const ::String &inName,const ::hx::Val &inValue,::hx::PropertyAccess inCallProp)
{
	switch(inName.length) {
	case 4:
		if (HX_FIELD_EQ(inName,"time") ) { if (inCallProp == ::hx::paccAlways) return ::hx::Val( set_time(inValue.Cast< ::cpp::Int64 >()) ); }
		if (HX_FIELD_EQ(inName,"rate") ) { if (inCallProp == ::hx::paccAlways) return ::hx::Val( set_rate(inValue.Cast< float >()) ); }
		break;
	case 6:
		if (HX_FIELD_EQ(inName,"volume") ) { if (inCallProp == ::hx::paccAlways) return ::hx::Val( set_volume(inValue.Cast< float >()) ); }
		break;
	case 7:
		if (HX_FIELD_EQ(inName,"members") ) { members=inValue.Cast< ::Array< ::Dynamic> >(); return inValue; }
		if (HX_FIELD_EQ(inName,"_volume") ) { _volume=inValue.Cast< float >(); return inValue; }
		break;
	case 8:
		if (HX_FIELD_EQ(inName,"onPaused") ) { onPaused=inValue.Cast<  ::lime::app::_Event_Void_Void >(); return inValue; }
		if (HX_FIELD_EQ(inName,"position") ) { if (inCallProp == ::hx::paccAlways) return ::hx::Val( set_position(inValue.Cast< float >()) ); }
		break;
	case 9:
		if (HX_FIELD_EQ(inName,"onOpening") ) { onOpening=inValue.Cast<  ::lime::app::_Event_Void_Void >(); return inValue; }
		if (HX_FIELD_EQ(inName,"onPlaying") ) { onPlaying=inValue.Cast<  ::lime::app::_Event_Void_Void >(); return inValue; }
		if (HX_FIELD_EQ(inName,"onStopped") ) { onStopped=inValue.Cast<  ::lime::app::_Event_Void_Void >(); return inValue; }
		break;
	case 11:
		if (HX_FIELD_EQ(inName,"autoDestroy") ) { autoDestroy=inValue.Cast< bool >(); return inValue; }
		break;
	case 12:
		if (HX_FIELD_EQ(inName,"onEndReached") ) { onEndReached=inValue.Cast<  ::lime::app::_Event_Void_Void >(); return inValue; }
		if (HX_FIELD_EQ(inName,"_firstMember") ) { _firstMember=inValue.Cast<  ::hxvlc::openfl::Audio >(); return inValue; }
		break;
	case 13:
		if (HX_FIELD_EQ(inName,"onTimeChanged") ) { onTimeChanged=inValue.Cast<  ::lime::app::_Event_haxe_Int64_Void >(); return inValue; }
		break;
	case 15:
		if (HX_FIELD_EQ(inName,"onLengthChanged") ) { onLengthChanged=inValue.Cast<  ::lime::app::_Event_haxe_Int64_Void >(); return inValue; }
		if (HX_FIELD_EQ(inName,"_dispatchPaused") ) { _dispatchPaused=inValue.Cast<  ::Dynamic >(); return inValue; }
		break;
	case 16:
		if (HX_FIELD_EQ(inName,"_dispatchOpening") ) { _dispatchOpening=inValue.Cast<  ::Dynamic >(); return inValue; }
		if (HX_FIELD_EQ(inName,"_dispatchPlaying") ) { _dispatchPlaying=inValue.Cast<  ::Dynamic >(); return inValue; }
		if (HX_FIELD_EQ(inName,"_dispatchStopped") ) { _dispatchStopped=inValue.Cast<  ::Dynamic >(); return inValue; }
		break;
	case 17:
		if (HX_FIELD_EQ(inName,"onPositionChanged") ) { onPositionChanged=inValue.Cast<  ::lime::app::_Event_Single_Void >(); return inValue; }
		break;
	case 18:
		if (HX_FIELD_EQ(inName,"onEncounteredError") ) { onEncounteredError=inValue.Cast<  ::lime::app::_Event_String_Void >(); return inValue; }
		break;
	case 19:
		if (HX_FIELD_EQ(inName,"_dispatchEndReached") ) { _dispatchEndReached=inValue.Cast<  ::Dynamic >(); return inValue; }
		break;
	case 20:
		if (HX_FIELD_EQ(inName,"_dispatchTimeChanged") ) { _dispatchTimeChanged=inValue.Cast<  ::Dynamic >(); return inValue; }
		break;
	case 22:
		if (HX_FIELD_EQ(inName,"_dispatchLengthChanged") ) { _dispatchLengthChanged=inValue.Cast<  ::Dynamic >(); return inValue; }
		break;
	case 24:
		if (HX_FIELD_EQ(inName,"_dispatchPositionChanged") ) { _dispatchPositionChanged=inValue.Cast<  ::Dynamic >(); return inValue; }
		break;
	case 25:
		if (HX_FIELD_EQ(inName,"_dispatchEncounteredError") ) { _dispatchEncounteredError=inValue.Cast<  ::Dynamic >(); return inValue; }
	}
	return super::__SetField(inName,inValue,inCallProp);
}

void AudioGroup_obj::__GetFields(Array< ::String> &outFields)
{
	outFields->push(HX_("members",d9,2c,70,1a));
	outFields->push(HX_("onOpening",f9,bb,ef,17));
	outFields->push(HX_("onPlaying",0f,c8,c2,61));
	outFields->push(HX_("onStopped",ae,8a,0c,1b));
	outFields->push(HX_("onPaused",2d,37,31,cf));
	outFields->push(HX_("onEndReached",f6,c1,9d,80));
	outFields->push(HX_("onEncounteredError",d5,1c,32,23));
	outFields->push(HX_("onTimeChanged",88,75,0c,a2));
	outFields->push(HX_("onPositionChanged",ec,50,fa,8a));
	outFields->push(HX_("onLengthChanged",0f,b4,c7,0e));
	outFields->push(HX_("length",e6,94,07,9f));
	outFields->push(HX_("duration",54,0f,8e,14));
	outFields->push(HX_("time",0d,cc,fc,4c));
	outFields->push(HX_("position",a9,a0,fa,ca));
	outFields->push(HX_("volume",da,29,53,5f));
	outFields->push(HX_("rate",e0,52,a4,4b));
	outFields->push(HX_("isPlaying",a4,8c,16,8e));
	outFields->push(HX_("autoDestroy",4b,d1,69,0a));
	outFields->push(HX_("_firstMember",ab,c0,61,4f));
	outFields->push(HX_("_volume",79,3b,ca,cd));
	super::__GetFields(outFields);
};

#ifdef HXCPP_SCRIPTABLE
static ::hx::StorageInfo AudioGroup_obj_sMemberStorageInfo[] = {
	{::hx::fsObject /* ::Array< ::Dynamic> */ ,(int)offsetof(AudioGroup_obj,members),HX_("members",d9,2c,70,1a)},
	{::hx::fsObject /*  ::lime::app::_Event_Void_Void */ ,(int)offsetof(AudioGroup_obj,onOpening),HX_("onOpening",f9,bb,ef,17)},
	{::hx::fsObject /*  ::lime::app::_Event_Void_Void */ ,(int)offsetof(AudioGroup_obj,onPlaying),HX_("onPlaying",0f,c8,c2,61)},
	{::hx::fsObject /*  ::lime::app::_Event_Void_Void */ ,(int)offsetof(AudioGroup_obj,onStopped),HX_("onStopped",ae,8a,0c,1b)},
	{::hx::fsObject /*  ::lime::app::_Event_Void_Void */ ,(int)offsetof(AudioGroup_obj,onPaused),HX_("onPaused",2d,37,31,cf)},
	{::hx::fsObject /*  ::lime::app::_Event_Void_Void */ ,(int)offsetof(AudioGroup_obj,onEndReached),HX_("onEndReached",f6,c1,9d,80)},
	{::hx::fsObject /*  ::lime::app::_Event_String_Void */ ,(int)offsetof(AudioGroup_obj,onEncounteredError),HX_("onEncounteredError",d5,1c,32,23)},
	{::hx::fsObject /*  ::lime::app::_Event_haxe_Int64_Void */ ,(int)offsetof(AudioGroup_obj,onTimeChanged),HX_("onTimeChanged",88,75,0c,a2)},
	{::hx::fsObject /*  ::lime::app::_Event_Single_Void */ ,(int)offsetof(AudioGroup_obj,onPositionChanged),HX_("onPositionChanged",ec,50,fa,8a)},
	{::hx::fsObject /*  ::lime::app::_Event_haxe_Int64_Void */ ,(int)offsetof(AudioGroup_obj,onLengthChanged),HX_("onLengthChanged",0f,b4,c7,0e)},
	{::hx::fsBool,(int)offsetof(AudioGroup_obj,autoDestroy),HX_("autoDestroy",4b,d1,69,0a)},
	{::hx::fsObject /*  ::hxvlc::openfl::Audio */ ,(int)offsetof(AudioGroup_obj,_firstMember),HX_("_firstMember",ab,c0,61,4f)},
	{::hx::fsUnknown /* float */ ,(int)offsetof(AudioGroup_obj,_volume),HX_("_volume",79,3b,ca,cd)},
	{::hx::fsObject /*  ::Dynamic */ ,(int)offsetof(AudioGroup_obj,_dispatchOpening),HX_("_dispatchOpening",3f,4a,ee,e2)},
	{::hx::fsObject /*  ::Dynamic */ ,(int)offsetof(AudioGroup_obj,_dispatchPlaying),HX_("_dispatchPlaying",55,56,c1,2c)},
	{::hx::fsObject /*  ::Dynamic */ ,(int)offsetof(AudioGroup_obj,_dispatchStopped),HX_("_dispatchStopped",f4,18,0b,e6)},
	{::hx::fsObject /*  ::Dynamic */ ,(int)offsetof(AudioGroup_obj,_dispatchPaused),HX_("_dispatchPaused",a7,93,43,74)},
	{::hx::fsObject /*  ::Dynamic */ ,(int)offsetof(AudioGroup_obj,_dispatchEndReached),HX_("_dispatchEndReached",70,e3,f0,32)},
	{::hx::fsObject /*  ::Dynamic */ ,(int)offsetof(AudioGroup_obj,_dispatchEncounteredError),HX_("_dispatchEncounteredError",cf,95,4e,eb)},
	{::hx::fsObject /*  ::Dynamic */ ,(int)offsetof(AudioGroup_obj,_dispatchTimeChanged),HX_("_dispatchTimeChanged",ce,9e,76,f8)},
	{::hx::fsObject /*  ::Dynamic */ ,(int)offsetof(AudioGroup_obj,_dispatchPositionChanged),HX_("_dispatchPositionChanged",32,95,39,1a)},
	{::hx::fsObject /*  ::Dynamic */ ,(int)offsetof(AudioGroup_obj,_dispatchLengthChanged),HX_("_dispatchLengthChanged",d5,3a,03,73)},
	{ ::hx::fsUnknown, 0, null()}
};
static ::hx::StaticInfo *AudioGroup_obj_sStaticStorageInfo = 0;
#endif

static ::String AudioGroup_obj_sMemberFields[] = {
	HX_("members",d9,2c,70,1a),
	HX_("onOpening",f9,bb,ef,17),
	HX_("onPlaying",0f,c8,c2,61),
	HX_("onStopped",ae,8a,0c,1b),
	HX_("onPaused",2d,37,31,cf),
	HX_("onEndReached",f6,c1,9d,80),
	HX_("onEncounteredError",d5,1c,32,23),
	HX_("onTimeChanged",88,75,0c,a2),
	HX_("onPositionChanged",ec,50,fa,8a),
	HX_("onLengthChanged",0f,b4,c7,0e),
	HX_("autoDestroy",4b,d1,69,0a),
	HX_("_firstMember",ab,c0,61,4f),
	HX_("_volume",79,3b,ca,cd),
	HX_("_dispatchOpening",3f,4a,ee,e2),
	HX_("_dispatchPlaying",55,56,c1,2c),
	HX_("_dispatchStopped",f4,18,0b,e6),
	HX_("_dispatchPaused",a7,93,43,74),
	HX_("_dispatchEndReached",70,e3,f0,32),
	HX_("_dispatchEncounteredError",cf,95,4e,eb),
	HX_("_dispatchTimeChanged",ce,9e,76,f8),
	HX_("_dispatchPositionChanged",32,95,39,1a),
	HX_("_dispatchLengthChanged",d5,3a,03,73),
	HX_("add",21,f2,49,00),
	HX_("remove",44,9c,88,04),
	HX_("addTrack",aa,b4,7c,8f),
	HX_("addTrackAsync",32,92,0d,be),
	HX_("releaseMedia",9d,9d,de,cc),
	HX_("play",f4,2d,5a,4a),
	HX_("pause",f6,d6,57,bd),
	HX_("resume",ad,69,84,08),
	HX_("stop",02,f0,5b,4c),
	HX_("setTime",cf,0c,81,12),
	HX_("dispose",9f,80,4c,bb),
	HX_("get_length",af,04,8f,8f),
	HX_("get_duration",5d,c3,a7,c9),
	HX_("get_time",96,87,b7,cc),
	HX_("set_time",0a,e1,14,7b),
	HX_("get_position",b2,54,14,80),
	HX_("set_position",26,78,0d,95),
	HX_("get_volume",a3,99,da,4f),
	HX_("set_volume",17,38,58,53),
	HX_("get_rate",69,0e,5f,cb),
	HX_("set_rate",dd,67,bc,79),
	HX_("get_isPlaying",7b,60,7a,4f),
	HX_("updateFirstMemberListeners",1e,1a,89,60),
	HX_("detachFirstMemberListeners",68,12,c4,1a),
	HX_("attachFirstMemberListeners",da,55,4b,0a),
	::String(null()) };

::hx::Class AudioGroup_obj::__mClass;

void AudioGroup_obj::__register()
{
	AudioGroup_obj _hx_dummy;
	AudioGroup_obj::_hx_vtable = *(void **)&_hx_dummy;
	::hx::Static(__mClass) = new ::hx::Class_obj();
	__mClass->mName = HX_("hxvlc.openfl.AudioGroup",76,31,c3,ac);
	__mClass->mSuper = &super::__SGetClass();
	__mClass->mConstructEmpty = &__CreateEmpty;
	__mClass->mConstructArgs = &__Create;
	__mClass->mGetStaticField = &::hx::Class_obj::GetNoStaticField;
	__mClass->mSetStaticField = &::hx::Class_obj::SetNoStaticField;
	__mClass->mStatics = ::hx::Class_obj::dupFunctions(0 /* sStaticFields */);
	__mClass->mMembers = ::hx::Class_obj::dupFunctions(AudioGroup_obj_sMemberFields);
	__mClass->mCanCast = ::hx::TCanCast< AudioGroup_obj >;
#ifdef HXCPP_SCRIPTABLE
	__mClass->mMemberStorageInfo = AudioGroup_obj_sMemberStorageInfo;
#endif
#ifdef HXCPP_SCRIPTABLE
	__mClass->mStaticStorageInfo = AudioGroup_obj_sStaticStorageInfo;
#endif
	::hx::_hx_RegisterClass(__mClass->mName, __mClass);
}

} // end namespace hxvlc
} // end namespace openfl
