// Generated by Haxe 4.3.7
#include <hxcpp.h>

#ifndef INCLUDED_CompileAudioGroup
#include <CompileAudioGroup.h>
#endif
#ifndef INCLUDED_hxvlc_openfl_Audio
#include <hxvlc/openfl/Audio.h>
#endif
#ifndef INCLUDED_hxvlc_openfl_AudioGroup
#include <hxvlc/openfl/AudioGroup.h>
#endif
#ifndef INCLUDED_openfl_events_EventDispatcher
#include <openfl/events/EventDispatcher.h>
#endif
#ifndef INCLUDED_openfl_events_IEventDispatcher
#include <openfl/events/IEventDispatcher.h>
#endif

HX_LOCAL_STACK_FRAME(_hx_pos_0ee28bd81c666ff6_9_main,"CompileAudioGroup","main",0x1b8fe42b,"CompileAudioGroup.main","CompileAudioGroup.hx",9,0x5132c682)

void CompileAudioGroup_obj::__construct() { }

Dynamic CompileAudioGroup_obj::__CreateEmpty() { return new CompileAudioGroup_obj; }

void *CompileAudioGroup_obj::_hx_vtable = 0;

Dynamic CompileAudioGroup_obj::__Create(::hx::DynamicArray inArgs)
{
	::hx::ObjectPtr< CompileAudioGroup_obj > _hx_result = new CompileAudioGroup_obj();
	_hx_result->__construct();
	return _hx_result;
}

bool CompileAudioGroup_obj::_hx_isInstanceOf(int inClassId) {
	return inClassId==(int)0x00000001 || inClassId==(int)0x7f8a5cb4;
}

void CompileAudioGroup_obj::main(){
            	HX_GC_STACKFRAME(&_hx_pos_0ee28bd81c666ff6_9_main)
HXLINE(  10)		 ::hxvlc::openfl::AudioGroup group =  ::hxvlc::openfl::AudioGroup_obj::__alloc( HX_CTX );
HXLINE(  11)		 ::hxvlc::openfl::Audio a =  ::hxvlc::openfl::Audio_obj::__alloc( HX_CTX );
HXLINE(  13)		group->add(a);
HXLINE(  14)		group->set_volume(( (float)(((Float)0.5)) ));
HXLINE(  15)		group->remove(a);
HXLINE(  16)		group->dispose();
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC0(CompileAudioGroup_obj,main,(void))


CompileAudioGroup_obj::CompileAudioGroup_obj()
{
}

bool CompileAudioGroup_obj::__GetStatic(const ::String &inName, Dynamic &outValue, ::hx::PropertyAccess inCallProp)
{
	switch(inName.length) {
	case 4:
		if (HX_FIELD_EQ(inName,"main") ) { outValue = main_dyn(); return true; }
	}
	return false;
}

#ifdef HXCPP_SCRIPTABLE
static ::hx::StorageInfo *CompileAudioGroup_obj_sMemberStorageInfo = 0;
static ::hx::StaticInfo *CompileAudioGroup_obj_sStaticStorageInfo = 0;
#endif

::hx::Class CompileAudioGroup_obj::__mClass;

static ::String CompileAudioGroup_obj_sStaticFields[] = {
	HX_("main",39,38,56,48),
	::String(null())
};

void CompileAudioGroup_obj::__register()
{
	CompileAudioGroup_obj _hx_dummy;
	CompileAudioGroup_obj::_hx_vtable = *(void **)&_hx_dummy;
	::hx::Static(__mClass) = new ::hx::Class_obj();
	__mClass->mName = HX_("CompileAudioGroup",bc,39,1e,9f);
	__mClass->mSuper = &super::__SGetClass();
	__mClass->mConstructEmpty = &__CreateEmpty;
	__mClass->mConstructArgs = &__Create;
	__mClass->mGetStaticField = &CompileAudioGroup_obj::__GetStatic;
	__mClass->mSetStaticField = &::hx::Class_obj::SetNoStaticField;
	__mClass->mStatics = ::hx::Class_obj::dupFunctions(CompileAudioGroup_obj_sStaticFields);
	__mClass->mMembers = ::hx::Class_obj::dupFunctions(0 /* sMemberFields */);
	__mClass->mCanCast = ::hx::TCanCast< CompileAudioGroup_obj >;
#ifdef HXCPP_SCRIPTABLE
	__mClass->mMemberStorageInfo = CompileAudioGroup_obj_sMemberStorageInfo;
#endif
#ifdef HXCPP_SCRIPTABLE
	__mClass->mStaticStorageInfo = CompileAudioGroup_obj_sStaticStorageInfo;
#endif
	::hx::_hx_RegisterClass(__mClass->mName, __mClass);
}

