// Generated by Haxe 4.3.7
#ifndef INCLUDED_CompileAudioGroup
#define INCLUDED_CompileAudioGroup

#ifndef HXCPP_H
#include <hxcpp.h>
#endif

HX_DECLARE_CLASS0(CompileAudioGroup)



class HXCPP_CLASS_ATTRIBUTES CompileAudioGroup_obj : public ::hx::Object
{
	public:
		typedef ::hx::Object super;
		typedef CompileAudioGroup_obj OBJ_;
		CompileAudioGroup_obj();

	public:
		enum { _hx_ClassId = 0x7f8a5cb4 };

		void __construct();
		inline void *operator new(size_t inSize, bool inContainer=false,const char *inName="CompileAudioGroup")
			{ return ::hx::Object::operator new(inSize,inContainer,inName); }
		inline void *operator new(size_t inSize, int extra)
			{ return ::hx::Object::operator new(inSize+extra,false,"CompileAudioGroup"); }

		inline static ::hx::ObjectPtr< CompileAudioGroup_obj > __new() {
			::hx::ObjectPtr< CompileAudioGroup_obj > __this = new CompileAudioGroup_obj();
			__this->__construct();
			return __this;
		}

		inline static ::hx::ObjectPtr< CompileAudioGroup_obj > __alloc(::hx::Ctx *_hx_ctx) {
			CompileAudioGroup_obj *__this = (CompileAudioGroup_obj*)(::hx::Ctx::alloc(_hx_ctx, sizeof(CompileAudioGroup_obj), false, "CompileAudioGroup"));
			*(void **)__this = CompileAudioGroup_obj::_hx_vtable;
			return __this;
		}

		static void * _hx_vtable;
		static Dynamic __CreateEmpty();
		static Dynamic __Create(::hx::DynamicArray inArgs);
		//~CompileAudioGroup_obj();

		HX_DO_RTTI_ALL;
		static bool __GetStatic(const ::String &inString, Dynamic &outValue, ::hx::PropertyAccess inCallProp);
		static void __register();
		bool _hx_isInstanceOf(int inClassId);
		::String __ToString() const { return HX_("CompileAudioGroup",bc,39,1e,9f); }

		static void main();
		static ::Dynamic main_dyn();

};


#endif /* INCLUDED_CompileAudioGroup */ 
